// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/internal/identity/ports/user_attribute_value.go
//
// Generated by this command:
//
//	mockgen -source=./api/internal/identity/ports/user_attribute_value.go -destination=./api/internal/identity/mocks/mock_user_attribute_value.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/huynhanx03/judgify/internal/identity/core/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserAttributeValueRepository is a mock of UserAttributeValueRepository interface.
type MockUserAttributeValueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserAttributeValueRepositoryMockRecorder
	isgomock struct{}
}

// MockUserAttributeValueRepositoryMockRecorder is the mock recorder for MockUserAttributeValueRepository.
type MockUserAttributeValueRepositoryMockRecorder struct {
	mock *MockUserAttributeValueRepository
}

// NewMockUserAttributeValueRepository creates a new mock instance.
func NewMockUserAttributeValueRepository(ctrl *gomock.Controller) *MockUserAttributeValueRepository {
	mock := &MockUserAttributeValueRepository{ctrl: ctrl}
	mock.recorder = &MockUserAttributeValueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAttributeValueRepository) EXPECT() *MockUserAttributeValueRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserAttributeValueRepository) Create(ctx context.Context, e *entity.UserAttributeValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserAttributeValueRepositoryMockRecorder) Create(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserAttributeValueRepository)(nil).Create), ctx, e)
}

// CreateBulk mocks base method.
func (m *MockUserAttributeValueRepository) CreateBulk(ctx context.Context, entities []*entity.UserAttributeValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBulk", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBulk indicates an expected call of CreateBulk.
func (mr *MockUserAttributeValueRepositoryMockRecorder) CreateBulk(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBulk", reflect.TypeOf((*MockUserAttributeValueRepository)(nil).CreateBulk), ctx, entities)
}

// Delete mocks base method.
func (m *MockUserAttributeValueRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserAttributeValueRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserAttributeValueRepository)(nil).Delete), ctx, id)
}

// DeleteByUserID mocks base method.
func (m *MockUserAttributeValueRepository) DeleteByUserID(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockUserAttributeValueRepositoryMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockUserAttributeValueRepository)(nil).DeleteByUserID), ctx, userID)
}

// Get mocks base method.
func (m *MockUserAttributeValueRepository) Get(ctx context.Context, id int) (*entity.UserAttributeValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.UserAttributeValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserAttributeValueRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserAttributeValueRepository)(nil).Get), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockUserAttributeValueRepository) GetByUserID(ctx context.Context, userID int) ([]*entity.UserAttributeValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entity.UserAttributeValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserAttributeValueRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserAttributeValueRepository)(nil).GetByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockUserAttributeValueRepository) Update(ctx context.Context, e *entity.UserAttributeValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserAttributeValueRepositoryMockRecorder) Update(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserAttributeValueRepository)(nil).Update), ctx, e)
}

// UpdateBulk mocks base method.
func (m *MockUserAttributeValueRepository) UpdateBulk(ctx context.Context, entities []*entity.UserAttributeValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBulk", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockUserAttributeValueRepositoryMockRecorder) UpdateBulk(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockUserAttributeValueRepository)(nil).UpdateBulk), ctx, entities)
}
