// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AttributeDefinition is the predicate function for attributedefinition builders.
type AttributeDefinition func(*sql.Selector)

// Credential is the predicate function for credential builders.
type Credential func(*sql.Selector)

// FederatedIdentity is the predicate function for federatedidentity builders.
type FederatedIdentity func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// Problem is the predicate function for problem builders.
type Problem func(*sql.Selector)

// Resource is the predicate function for resource builders.
type Resource func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// TestCase is the predicate function for testcase builders.
type TestCase func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserAttributeValue is the predicate function for userattributevalue builders.
type UserAttributeValue func(*sql.Selector)
