// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/huynhanx03/judgify/internal/ent/generate/contest"
	"github.com/huynhanx03/judgify/internal/ent/generate/conteststanding"
	"github.com/huynhanx03/judgify/internal/ent/generate/user"
)

// ContestStandingCreate is the builder for creating a ContestStanding entity.
type ContestStandingCreate struct {
	config
	mutation *ContestStandingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetContestID sets the "contest_id" field.
func (_c *ContestStandingCreate) SetContestID(v int) *ContestStandingCreate {
	_c.mutation.SetContestID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ContestStandingCreate) SetUserID(v int) *ContestStandingCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSolvedCount sets the "solved_count" field.
func (_c *ContestStandingCreate) SetSolvedCount(v int) *ContestStandingCreate {
	_c.mutation.SetSolvedCount(v)
	return _c
}

// SetNillableSolvedCount sets the "solved_count" field if the given value is not nil.
func (_c *ContestStandingCreate) SetNillableSolvedCount(v *int) *ContestStandingCreate {
	if v != nil {
		_c.SetSolvedCount(*v)
	}
	return _c
}

// SetPenalty sets the "penalty" field.
func (_c *ContestStandingCreate) SetPenalty(v int) *ContestStandingCreate {
	_c.mutation.SetPenalty(v)
	return _c
}

// SetNillablePenalty sets the "penalty" field if the given value is not nil.
func (_c *ContestStandingCreate) SetNillablePenalty(v *int) *ContestStandingCreate {
	if v != nil {
		_c.SetPenalty(*v)
	}
	return _c
}

// SetProblemResults sets the "problem_results" field.
func (_c *ContestStandingCreate) SetProblemResults(v map[string]interface{}) *ContestStandingCreate {
	_c.mutation.SetProblemResults(v)
	return _c
}

// SetContest sets the "contest" edge to the Contest entity.
func (_c *ContestStandingCreate) SetContest(v *Contest) *ContestStandingCreate {
	return _c.SetContestID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *ContestStandingCreate) SetUser(v *User) *ContestStandingCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ContestStandingMutation object of the builder.
func (_c *ContestStandingCreate) Mutation() *ContestStandingMutation {
	return _c.mutation
}

// Save creates the ContestStanding in the database.
func (_c *ContestStandingCreate) Save(ctx context.Context) (*ContestStanding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContestStandingCreate) SaveX(ctx context.Context) *ContestStanding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContestStandingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContestStandingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContestStandingCreate) defaults() {
	if _, ok := _c.mutation.SolvedCount(); !ok {
		v := conteststanding.DefaultSolvedCount
		_c.mutation.SetSolvedCount(v)
	}
	if _, ok := _c.mutation.Penalty(); !ok {
		v := conteststanding.DefaultPenalty
		_c.mutation.SetPenalty(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContestStandingCreate) check() error {
	if _, ok := _c.mutation.ContestID(); !ok {
		return &ValidationError{Name: "contest_id", err: errors.New(`generate: missing required field "ContestStanding.contest_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`generate: missing required field "ContestStanding.user_id"`)}
	}
	if _, ok := _c.mutation.SolvedCount(); !ok {
		return &ValidationError{Name: "solved_count", err: errors.New(`generate: missing required field "ContestStanding.solved_count"`)}
	}
	if _, ok := _c.mutation.Penalty(); !ok {
		return &ValidationError{Name: "penalty", err: errors.New(`generate: missing required field "ContestStanding.penalty"`)}
	}
	if len(_c.mutation.ContestIDs()) == 0 {
		return &ValidationError{Name: "contest", err: errors.New(`generate: missing required edge "ContestStanding.contest"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`generate: missing required edge "ContestStanding.user"`)}
	}
	return nil
}

func (_c *ContestStandingCreate) sqlSave(ctx context.Context) (*ContestStanding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContestStandingCreate) createSpec() (*ContestStanding, *sqlgraph.CreateSpec) {
	var (
		_node = &ContestStanding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(conteststanding.Table, sqlgraph.NewFieldSpec(conteststanding.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SolvedCount(); ok {
		_spec.SetField(conteststanding.FieldSolvedCount, field.TypeInt, value)
		_node.SolvedCount = value
	}
	if value, ok := _c.mutation.Penalty(); ok {
		_spec.SetField(conteststanding.FieldPenalty, field.TypeInt, value)
		_node.Penalty = value
	}
	if value, ok := _c.mutation.ProblemResults(); ok {
		_spec.SetField(conteststanding.FieldProblemResults, field.TypeJSON, value)
		_node.ProblemResults = value
	}
	if nodes := _c.mutation.ContestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conteststanding.ContestTable,
			Columns: []string{conteststanding.ContestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ContestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conteststanding.UserTable,
			Columns: []string{conteststanding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContestStanding.Create().
//		SetContestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContestStandingUpsert) {
//			SetContestID(v+v).
//		}).
//		Exec(ctx)
func (_c *ContestStandingCreate) OnConflict(opts ...sql.ConflictOption) *ContestStandingUpsertOne {
	_c.conflict = opts
	return &ContestStandingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContestStanding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContestStandingCreate) OnConflictColumns(columns ...string) *ContestStandingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContestStandingUpsertOne{
		create: _c,
	}
}

type (
	// ContestStandingUpsertOne is the builder for "upsert"-ing
	//  one ContestStanding node.
	ContestStandingUpsertOne struct {
		create *ContestStandingCreate
	}

	// ContestStandingUpsert is the "OnConflict" setter.
	ContestStandingUpsert struct {
		*sql.UpdateSet
	}
)

// SetContestID sets the "contest_id" field.
func (u *ContestStandingUpsert) SetContestID(v int) *ContestStandingUpsert {
	u.Set(conteststanding.FieldContestID, v)
	return u
}

// UpdateContestID sets the "contest_id" field to the value that was provided on create.
func (u *ContestStandingUpsert) UpdateContestID() *ContestStandingUpsert {
	u.SetExcluded(conteststanding.FieldContestID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ContestStandingUpsert) SetUserID(v int) *ContestStandingUpsert {
	u.Set(conteststanding.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ContestStandingUpsert) UpdateUserID() *ContestStandingUpsert {
	u.SetExcluded(conteststanding.FieldUserID)
	return u
}

// SetSolvedCount sets the "solved_count" field.
func (u *ContestStandingUpsert) SetSolvedCount(v int) *ContestStandingUpsert {
	u.Set(conteststanding.FieldSolvedCount, v)
	return u
}

// UpdateSolvedCount sets the "solved_count" field to the value that was provided on create.
func (u *ContestStandingUpsert) UpdateSolvedCount() *ContestStandingUpsert {
	u.SetExcluded(conteststanding.FieldSolvedCount)
	return u
}

// AddSolvedCount adds v to the "solved_count" field.
func (u *ContestStandingUpsert) AddSolvedCount(v int) *ContestStandingUpsert {
	u.Add(conteststanding.FieldSolvedCount, v)
	return u
}

// SetPenalty sets the "penalty" field.
func (u *ContestStandingUpsert) SetPenalty(v int) *ContestStandingUpsert {
	u.Set(conteststanding.FieldPenalty, v)
	return u
}

// UpdatePenalty sets the "penalty" field to the value that was provided on create.
func (u *ContestStandingUpsert) UpdatePenalty() *ContestStandingUpsert {
	u.SetExcluded(conteststanding.FieldPenalty)
	return u
}

// AddPenalty adds v to the "penalty" field.
func (u *ContestStandingUpsert) AddPenalty(v int) *ContestStandingUpsert {
	u.Add(conteststanding.FieldPenalty, v)
	return u
}

// SetProblemResults sets the "problem_results" field.
func (u *ContestStandingUpsert) SetProblemResults(v map[string]interface{}) *ContestStandingUpsert {
	u.Set(conteststanding.FieldProblemResults, v)
	return u
}

// UpdateProblemResults sets the "problem_results" field to the value that was provided on create.
func (u *ContestStandingUpsert) UpdateProblemResults() *ContestStandingUpsert {
	u.SetExcluded(conteststanding.FieldProblemResults)
	return u
}

// ClearProblemResults clears the value of the "problem_results" field.
func (u *ContestStandingUpsert) ClearProblemResults() *ContestStandingUpsert {
	u.SetNull(conteststanding.FieldProblemResults)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ContestStanding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContestStandingUpsertOne) UpdateNewValues() *ContestStandingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContestStanding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ContestStandingUpsertOne) Ignore() *ContestStandingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContestStandingUpsertOne) DoNothing() *ContestStandingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContestStandingCreate.OnConflict
// documentation for more info.
func (u *ContestStandingUpsertOne) Update(set func(*ContestStandingUpsert)) *ContestStandingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContestStandingUpsert{UpdateSet: update})
	}))
	return u
}

// SetContestID sets the "contest_id" field.
func (u *ContestStandingUpsertOne) SetContestID(v int) *ContestStandingUpsertOne {
	return u.Update(func(s *ContestStandingUpsert) {
		s.SetContestID(v)
	})
}

// UpdateContestID sets the "contest_id" field to the value that was provided on create.
func (u *ContestStandingUpsertOne) UpdateContestID() *ContestStandingUpsertOne {
	return u.Update(func(s *ContestStandingUpsert) {
		s.UpdateContestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ContestStandingUpsertOne) SetUserID(v int) *ContestStandingUpsertOne {
	return u.Update(func(s *ContestStandingUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ContestStandingUpsertOne) UpdateUserID() *ContestStandingUpsertOne {
	return u.Update(func(s *ContestStandingUpsert) {
		s.UpdateUserID()
	})
}

// SetSolvedCount sets the "solved_count" field.
func (u *ContestStandingUpsertOne) SetSolvedCount(v int) *ContestStandingUpsertOne {
	return u.Update(func(s *ContestStandingUpsert) {
		s.SetSolvedCount(v)
	})
}

// AddSolvedCount adds v to the "solved_count" field.
func (u *ContestStandingUpsertOne) AddSolvedCount(v int) *ContestStandingUpsertOne {
	return u.Update(func(s *ContestStandingUpsert) {
		s.AddSolvedCount(v)
	})
}

// UpdateSolvedCount sets the "solved_count" field to the value that was provided on create.
func (u *ContestStandingUpsertOne) UpdateSolvedCount() *ContestStandingUpsertOne {
	return u.Update(func(s *ContestStandingUpsert) {
		s.UpdateSolvedCount()
	})
}

// SetPenalty sets the "penalty" field.
func (u *ContestStandingUpsertOne) SetPenalty(v int) *ContestStandingUpsertOne {
	return u.Update(func(s *ContestStandingUpsert) {
		s.SetPenalty(v)
	})
}

// AddPenalty adds v to the "penalty" field.
func (u *ContestStandingUpsertOne) AddPenalty(v int) *ContestStandingUpsertOne {
	return u.Update(func(s *ContestStandingUpsert) {
		s.AddPenalty(v)
	})
}

// UpdatePenalty sets the "penalty" field to the value that was provided on create.
func (u *ContestStandingUpsertOne) UpdatePenalty() *ContestStandingUpsertOne {
	return u.Update(func(s *ContestStandingUpsert) {
		s.UpdatePenalty()
	})
}

// SetProblemResults sets the "problem_results" field.
func (u *ContestStandingUpsertOne) SetProblemResults(v map[string]interface{}) *ContestStandingUpsertOne {
	return u.Update(func(s *ContestStandingUpsert) {
		s.SetProblemResults(v)
	})
}

// UpdateProblemResults sets the "problem_results" field to the value that was provided on create.
func (u *ContestStandingUpsertOne) UpdateProblemResults() *ContestStandingUpsertOne {
	return u.Update(func(s *ContestStandingUpsert) {
		s.UpdateProblemResults()
	})
}

// ClearProblemResults clears the value of the "problem_results" field.
func (u *ContestStandingUpsertOne) ClearProblemResults() *ContestStandingUpsertOne {
	return u.Update(func(s *ContestStandingUpsert) {
		s.ClearProblemResults()
	})
}

// Exec executes the query.
func (u *ContestStandingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for ContestStandingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContestStandingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ContestStandingUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ContestStandingUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (c *ContestStandingCreate) SetID(id int) *ContestStandingCreate {
	c.mutation.id = &id
	return c
}

// ContestStandingCreateBulk is the builder for creating many ContestStanding entities in bulk.
type ContestStandingCreateBulk struct {
	config
	err      error
	builders []*ContestStandingCreate
	conflict []sql.ConflictOption
}

// Save creates the ContestStanding entities in the database.
func (_c *ContestStandingCreateBulk) Save(ctx context.Context) ([]*ContestStanding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContestStanding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContestStandingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContestStandingCreateBulk) SaveX(ctx context.Context) []*ContestStanding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContestStandingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContestStandingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContestStanding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContestStandingUpsert) {
//			SetContestID(v+v).
//		}).
//		Exec(ctx)
func (_c *ContestStandingCreateBulk) OnConflict(opts ...sql.ConflictOption) *ContestStandingUpsertBulk {
	_c.conflict = opts
	return &ContestStandingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContestStanding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContestStandingCreateBulk) OnConflictColumns(columns ...string) *ContestStandingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContestStandingUpsertBulk{
		create: _c,
	}
}

// ContestStandingUpsertBulk is the builder for "upsert"-ing
// a bulk of ContestStanding nodes.
type ContestStandingUpsertBulk struct {
	create *ContestStandingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ContestStanding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContestStandingUpsertBulk) UpdateNewValues() *ContestStandingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContestStanding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ContestStandingUpsertBulk) Ignore() *ContestStandingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContestStandingUpsertBulk) DoNothing() *ContestStandingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContestStandingCreateBulk.OnConflict
// documentation for more info.
func (u *ContestStandingUpsertBulk) Update(set func(*ContestStandingUpsert)) *ContestStandingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContestStandingUpsert{UpdateSet: update})
	}))
	return u
}

// SetContestID sets the "contest_id" field.
func (u *ContestStandingUpsertBulk) SetContestID(v int) *ContestStandingUpsertBulk {
	return u.Update(func(s *ContestStandingUpsert) {
		s.SetContestID(v)
	})
}

// UpdateContestID sets the "contest_id" field to the value that was provided on create.
func (u *ContestStandingUpsertBulk) UpdateContestID() *ContestStandingUpsertBulk {
	return u.Update(func(s *ContestStandingUpsert) {
		s.UpdateContestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ContestStandingUpsertBulk) SetUserID(v int) *ContestStandingUpsertBulk {
	return u.Update(func(s *ContestStandingUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ContestStandingUpsertBulk) UpdateUserID() *ContestStandingUpsertBulk {
	return u.Update(func(s *ContestStandingUpsert) {
		s.UpdateUserID()
	})
}

// SetSolvedCount sets the "solved_count" field.
func (u *ContestStandingUpsertBulk) SetSolvedCount(v int) *ContestStandingUpsertBulk {
	return u.Update(func(s *ContestStandingUpsert) {
		s.SetSolvedCount(v)
	})
}

// AddSolvedCount adds v to the "solved_count" field.
func (u *ContestStandingUpsertBulk) AddSolvedCount(v int) *ContestStandingUpsertBulk {
	return u.Update(func(s *ContestStandingUpsert) {
		s.AddSolvedCount(v)
	})
}

// UpdateSolvedCount sets the "solved_count" field to the value that was provided on create.
func (u *ContestStandingUpsertBulk) UpdateSolvedCount() *ContestStandingUpsertBulk {
	return u.Update(func(s *ContestStandingUpsert) {
		s.UpdateSolvedCount()
	})
}

// SetPenalty sets the "penalty" field.
func (u *ContestStandingUpsertBulk) SetPenalty(v int) *ContestStandingUpsertBulk {
	return u.Update(func(s *ContestStandingUpsert) {
		s.SetPenalty(v)
	})
}

// AddPenalty adds v to the "penalty" field.
func (u *ContestStandingUpsertBulk) AddPenalty(v int) *ContestStandingUpsertBulk {
	return u.Update(func(s *ContestStandingUpsert) {
		s.AddPenalty(v)
	})
}

// UpdatePenalty sets the "penalty" field to the value that was provided on create.
func (u *ContestStandingUpsertBulk) UpdatePenalty() *ContestStandingUpsertBulk {
	return u.Update(func(s *ContestStandingUpsert) {
		s.UpdatePenalty()
	})
}

// SetProblemResults sets the "problem_results" field.
func (u *ContestStandingUpsertBulk) SetProblemResults(v map[string]interface{}) *ContestStandingUpsertBulk {
	return u.Update(func(s *ContestStandingUpsert) {
		s.SetProblemResults(v)
	})
}

// UpdateProblemResults sets the "problem_results" field to the value that was provided on create.
func (u *ContestStandingUpsertBulk) UpdateProblemResults() *ContestStandingUpsertBulk {
	return u.Update(func(s *ContestStandingUpsert) {
		s.UpdateProblemResults()
	})
}

// ClearProblemResults clears the value of the "problem_results" field.
func (u *ContestStandingUpsertBulk) ClearProblemResults() *ContestStandingUpsertBulk {
	return u.Update(func(s *ContestStandingUpsert) {
		s.ClearProblemResults()
	})
}

// Exec executes the query.
func (u *ContestStandingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("generate: OnConflict was set for builder %d. Set it on the ContestStandingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for ContestStandingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContestStandingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
