// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/huynhanx03/judgify/internal/ent/generate/contest"
	"github.com/huynhanx03/judgify/internal/ent/generate/conteststanding"
	"github.com/huynhanx03/judgify/internal/ent/generate/predicate"
	"github.com/huynhanx03/judgify/internal/ent/generate/user"
)

// ContestStandingUpdate is the builder for updating ContestStanding entities.
type ContestStandingUpdate struct {
	config
	hooks     []Hook
	mutation  *ContestStandingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ContestStandingUpdate builder.
func (_u *ContestStandingUpdate) Where(ps ...predicate.ContestStanding) *ContestStandingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContestID sets the "contest_id" field.
func (_u *ContestStandingUpdate) SetContestID(v int) *ContestStandingUpdate {
	_u.mutation.SetContestID(v)
	return _u
}

// SetNillableContestID sets the "contest_id" field if the given value is not nil.
func (_u *ContestStandingUpdate) SetNillableContestID(v *int) *ContestStandingUpdate {
	if v != nil {
		_u.SetContestID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ContestStandingUpdate) SetUserID(v int) *ContestStandingUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ContestStandingUpdate) SetNillableUserID(v *int) *ContestStandingUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSolvedCount sets the "solved_count" field.
func (_u *ContestStandingUpdate) SetSolvedCount(v int) *ContestStandingUpdate {
	_u.mutation.ResetSolvedCount()
	_u.mutation.SetSolvedCount(v)
	return _u
}

// SetNillableSolvedCount sets the "solved_count" field if the given value is not nil.
func (_u *ContestStandingUpdate) SetNillableSolvedCount(v *int) *ContestStandingUpdate {
	if v != nil {
		_u.SetSolvedCount(*v)
	}
	return _u
}

// AddSolvedCount adds value to the "solved_count" field.
func (_u *ContestStandingUpdate) AddSolvedCount(v int) *ContestStandingUpdate {
	_u.mutation.AddSolvedCount(v)
	return _u
}

// SetPenalty sets the "penalty" field.
func (_u *ContestStandingUpdate) SetPenalty(v int) *ContestStandingUpdate {
	_u.mutation.ResetPenalty()
	_u.mutation.SetPenalty(v)
	return _u
}

// SetNillablePenalty sets the "penalty" field if the given value is not nil.
func (_u *ContestStandingUpdate) SetNillablePenalty(v *int) *ContestStandingUpdate {
	if v != nil {
		_u.SetPenalty(*v)
	}
	return _u
}

// AddPenalty adds value to the "penalty" field.
func (_u *ContestStandingUpdate) AddPenalty(v int) *ContestStandingUpdate {
	_u.mutation.AddPenalty(v)
	return _u
}

// SetProblemResults sets the "problem_results" field.
func (_u *ContestStandingUpdate) SetProblemResults(v map[string]interface{}) *ContestStandingUpdate {
	_u.mutation.SetProblemResults(v)
	return _u
}

// ClearProblemResults clears the value of the "problem_results" field.
func (_u *ContestStandingUpdate) ClearProblemResults() *ContestStandingUpdate {
	_u.mutation.ClearProblemResults()
	return _u
}

// SetContest sets the "contest" edge to the Contest entity.
func (_u *ContestStandingUpdate) SetContest(v *Contest) *ContestStandingUpdate {
	return _u.SetContestID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ContestStandingUpdate) SetUser(v *User) *ContestStandingUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ContestStandingMutation object of the builder.
func (_u *ContestStandingUpdate) Mutation() *ContestStandingMutation {
	return _u.mutation
}

// ClearContest clears the "contest" edge to the Contest entity.
func (_u *ContestStandingUpdate) ClearContest() *ContestStandingUpdate {
	_u.mutation.ClearContest()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ContestStandingUpdate) ClearUser() *ContestStandingUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContestStandingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContestStandingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContestStandingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContestStandingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContestStandingUpdate) check() error {
	if _u.mutation.ContestCleared() && len(_u.mutation.ContestIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "ContestStanding.contest"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "ContestStanding.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ContestStandingUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ContestStandingUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ContestStandingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conteststanding.Table, conteststanding.Columns, sqlgraph.NewFieldSpec(conteststanding.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SolvedCount(); ok {
		_spec.SetField(conteststanding.FieldSolvedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSolvedCount(); ok {
		_spec.AddField(conteststanding.FieldSolvedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Penalty(); ok {
		_spec.SetField(conteststanding.FieldPenalty, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPenalty(); ok {
		_spec.AddField(conteststanding.FieldPenalty, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProblemResults(); ok {
		_spec.SetField(conteststanding.FieldProblemResults, field.TypeJSON, value)
	}
	if _u.mutation.ProblemResultsCleared() {
		_spec.ClearField(conteststanding.FieldProblemResults, field.TypeJSON)
	}
	if _u.mutation.ContestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conteststanding.ContestTable,
			Columns: []string{conteststanding.ContestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conteststanding.ContestTable,
			Columns: []string{conteststanding.ContestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conteststanding.UserTable,
			Columns: []string{conteststanding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conteststanding.UserTable,
			Columns: []string{conteststanding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conteststanding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContestStandingUpdateOne is the builder for updating a single ContestStanding entity.
type ContestStandingUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ContestStandingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetContestID sets the "contest_id" field.
func (_u *ContestStandingUpdateOne) SetContestID(v int) *ContestStandingUpdateOne {
	_u.mutation.SetContestID(v)
	return _u
}

// SetNillableContestID sets the "contest_id" field if the given value is not nil.
func (_u *ContestStandingUpdateOne) SetNillableContestID(v *int) *ContestStandingUpdateOne {
	if v != nil {
		_u.SetContestID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ContestStandingUpdateOne) SetUserID(v int) *ContestStandingUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ContestStandingUpdateOne) SetNillableUserID(v *int) *ContestStandingUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSolvedCount sets the "solved_count" field.
func (_u *ContestStandingUpdateOne) SetSolvedCount(v int) *ContestStandingUpdateOne {
	_u.mutation.ResetSolvedCount()
	_u.mutation.SetSolvedCount(v)
	return _u
}

// SetNillableSolvedCount sets the "solved_count" field if the given value is not nil.
func (_u *ContestStandingUpdateOne) SetNillableSolvedCount(v *int) *ContestStandingUpdateOne {
	if v != nil {
		_u.SetSolvedCount(*v)
	}
	return _u
}

// AddSolvedCount adds value to the "solved_count" field.
func (_u *ContestStandingUpdateOne) AddSolvedCount(v int) *ContestStandingUpdateOne {
	_u.mutation.AddSolvedCount(v)
	return _u
}

// SetPenalty sets the "penalty" field.
func (_u *ContestStandingUpdateOne) SetPenalty(v int) *ContestStandingUpdateOne {
	_u.mutation.ResetPenalty()
	_u.mutation.SetPenalty(v)
	return _u
}

// SetNillablePenalty sets the "penalty" field if the given value is not nil.
func (_u *ContestStandingUpdateOne) SetNillablePenalty(v *int) *ContestStandingUpdateOne {
	if v != nil {
		_u.SetPenalty(*v)
	}
	return _u
}

// AddPenalty adds value to the "penalty" field.
func (_u *ContestStandingUpdateOne) AddPenalty(v int) *ContestStandingUpdateOne {
	_u.mutation.AddPenalty(v)
	return _u
}

// SetProblemResults sets the "problem_results" field.
func (_u *ContestStandingUpdateOne) SetProblemResults(v map[string]interface{}) *ContestStandingUpdateOne {
	_u.mutation.SetProblemResults(v)
	return _u
}

// ClearProblemResults clears the value of the "problem_results" field.
func (_u *ContestStandingUpdateOne) ClearProblemResults() *ContestStandingUpdateOne {
	_u.mutation.ClearProblemResults()
	return _u
}

// SetContest sets the "contest" edge to the Contest entity.
func (_u *ContestStandingUpdateOne) SetContest(v *Contest) *ContestStandingUpdateOne {
	return _u.SetContestID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ContestStandingUpdateOne) SetUser(v *User) *ContestStandingUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ContestStandingMutation object of the builder.
func (_u *ContestStandingUpdateOne) Mutation() *ContestStandingMutation {
	return _u.mutation
}

// ClearContest clears the "contest" edge to the Contest entity.
func (_u *ContestStandingUpdateOne) ClearContest() *ContestStandingUpdateOne {
	_u.mutation.ClearContest()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ContestStandingUpdateOne) ClearUser() *ContestStandingUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ContestStandingUpdate builder.
func (_u *ContestStandingUpdateOne) Where(ps ...predicate.ContestStanding) *ContestStandingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContestStandingUpdateOne) Select(field string, fields ...string) *ContestStandingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ContestStanding entity.
func (_u *ContestStandingUpdateOne) Save(ctx context.Context) (*ContestStanding, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContestStandingUpdateOne) SaveX(ctx context.Context) *ContestStanding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContestStandingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContestStandingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContestStandingUpdateOne) check() error {
	if _u.mutation.ContestCleared() && len(_u.mutation.ContestIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "ContestStanding.contest"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "ContestStanding.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ContestStandingUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ContestStandingUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ContestStandingUpdateOne) sqlSave(ctx context.Context) (_node *ContestStanding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conteststanding.Table, conteststanding.Columns, sqlgraph.NewFieldSpec(conteststanding.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`generate: missing "ContestStanding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conteststanding.FieldID)
		for _, f := range fields {
			if !conteststanding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("generate: invalid field %q for query", f)}
			}
			if f != conteststanding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SolvedCount(); ok {
		_spec.SetField(conteststanding.FieldSolvedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSolvedCount(); ok {
		_spec.AddField(conteststanding.FieldSolvedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Penalty(); ok {
		_spec.SetField(conteststanding.FieldPenalty, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPenalty(); ok {
		_spec.AddField(conteststanding.FieldPenalty, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProblemResults(); ok {
		_spec.SetField(conteststanding.FieldProblemResults, field.TypeJSON, value)
	}
	if _u.mutation.ProblemResultsCleared() {
		_spec.ClearField(conteststanding.FieldProblemResults, field.TypeJSON)
	}
	if _u.mutation.ContestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conteststanding.ContestTable,
			Columns: []string{conteststanding.ContestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conteststanding.ContestTable,
			Columns: []string{conteststanding.ContestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conteststanding.UserTable,
			Columns: []string{conteststanding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conteststanding.UserTable,
			Columns: []string{conteststanding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ContestStanding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conteststanding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
