// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/huynhanx03/judgify/internal/ent/generate/contest"
	"github.com/huynhanx03/judgify/internal/ent/generate/contestregistration"
	"github.com/huynhanx03/judgify/internal/ent/generate/user"
)

// ContestRegistrationCreate is the builder for creating a ContestRegistration entity.
type ContestRegistrationCreate struct {
	config
	mutation *ContestRegistrationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetContestID sets the "contest_id" field.
func (_c *ContestRegistrationCreate) SetContestID(v int) *ContestRegistrationCreate {
	_c.mutation.SetContestID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ContestRegistrationCreate) SetUserID(v int) *ContestRegistrationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetContest sets the "contest" edge to the Contest entity.
func (_c *ContestRegistrationCreate) SetContest(v *Contest) *ContestRegistrationCreate {
	return _c.SetContestID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *ContestRegistrationCreate) SetUser(v *User) *ContestRegistrationCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ContestRegistrationMutation object of the builder.
func (_c *ContestRegistrationCreate) Mutation() *ContestRegistrationMutation {
	return _c.mutation
}

// Save creates the ContestRegistration in the database.
func (_c *ContestRegistrationCreate) Save(ctx context.Context) (*ContestRegistration, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContestRegistrationCreate) SaveX(ctx context.Context) *ContestRegistration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContestRegistrationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContestRegistrationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContestRegistrationCreate) check() error {
	if _, ok := _c.mutation.ContestID(); !ok {
		return &ValidationError{Name: "contest_id", err: errors.New(`generate: missing required field "ContestRegistration.contest_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`generate: missing required field "ContestRegistration.user_id"`)}
	}
	if len(_c.mutation.ContestIDs()) == 0 {
		return &ValidationError{Name: "contest", err: errors.New(`generate: missing required edge "ContestRegistration.contest"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`generate: missing required edge "ContestRegistration.user"`)}
	}
	return nil
}

func (_c *ContestRegistrationCreate) sqlSave(ctx context.Context) (*ContestRegistration, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContestRegistrationCreate) createSpec() (*ContestRegistration, *sqlgraph.CreateSpec) {
	var (
		_node = &ContestRegistration{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contestregistration.Table, sqlgraph.NewFieldSpec(contestregistration.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if nodes := _c.mutation.ContestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contestregistration.ContestTable,
			Columns: []string{contestregistration.ContestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ContestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contestregistration.UserTable,
			Columns: []string{contestregistration.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContestRegistration.Create().
//		SetContestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContestRegistrationUpsert) {
//			SetContestID(v+v).
//		}).
//		Exec(ctx)
func (_c *ContestRegistrationCreate) OnConflict(opts ...sql.ConflictOption) *ContestRegistrationUpsertOne {
	_c.conflict = opts
	return &ContestRegistrationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContestRegistration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContestRegistrationCreate) OnConflictColumns(columns ...string) *ContestRegistrationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContestRegistrationUpsertOne{
		create: _c,
	}
}

type (
	// ContestRegistrationUpsertOne is the builder for "upsert"-ing
	//  one ContestRegistration node.
	ContestRegistrationUpsertOne struct {
		create *ContestRegistrationCreate
	}

	// ContestRegistrationUpsert is the "OnConflict" setter.
	ContestRegistrationUpsert struct {
		*sql.UpdateSet
	}
)

// SetContestID sets the "contest_id" field.
func (u *ContestRegistrationUpsert) SetContestID(v int) *ContestRegistrationUpsert {
	u.Set(contestregistration.FieldContestID, v)
	return u
}

// UpdateContestID sets the "contest_id" field to the value that was provided on create.
func (u *ContestRegistrationUpsert) UpdateContestID() *ContestRegistrationUpsert {
	u.SetExcluded(contestregistration.FieldContestID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ContestRegistrationUpsert) SetUserID(v int) *ContestRegistrationUpsert {
	u.Set(contestregistration.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ContestRegistrationUpsert) UpdateUserID() *ContestRegistrationUpsert {
	u.SetExcluded(contestregistration.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ContestRegistration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContestRegistrationUpsertOne) UpdateNewValues() *ContestRegistrationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContestRegistration.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ContestRegistrationUpsertOne) Ignore() *ContestRegistrationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContestRegistrationUpsertOne) DoNothing() *ContestRegistrationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContestRegistrationCreate.OnConflict
// documentation for more info.
func (u *ContestRegistrationUpsertOne) Update(set func(*ContestRegistrationUpsert)) *ContestRegistrationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContestRegistrationUpsert{UpdateSet: update})
	}))
	return u
}

// SetContestID sets the "contest_id" field.
func (u *ContestRegistrationUpsertOne) SetContestID(v int) *ContestRegistrationUpsertOne {
	return u.Update(func(s *ContestRegistrationUpsert) {
		s.SetContestID(v)
	})
}

// UpdateContestID sets the "contest_id" field to the value that was provided on create.
func (u *ContestRegistrationUpsertOne) UpdateContestID() *ContestRegistrationUpsertOne {
	return u.Update(func(s *ContestRegistrationUpsert) {
		s.UpdateContestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ContestRegistrationUpsertOne) SetUserID(v int) *ContestRegistrationUpsertOne {
	return u.Update(func(s *ContestRegistrationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ContestRegistrationUpsertOne) UpdateUserID() *ContestRegistrationUpsertOne {
	return u.Update(func(s *ContestRegistrationUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *ContestRegistrationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for ContestRegistrationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContestRegistrationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ContestRegistrationUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ContestRegistrationUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (c *ContestRegistrationCreate) SetID(id int) *ContestRegistrationCreate {
	c.mutation.id = &id
	return c
}

// ContestRegistrationCreateBulk is the builder for creating many ContestRegistration entities in bulk.
type ContestRegistrationCreateBulk struct {
	config
	err      error
	builders []*ContestRegistrationCreate
	conflict []sql.ConflictOption
}

// Save creates the ContestRegistration entities in the database.
func (_c *ContestRegistrationCreateBulk) Save(ctx context.Context) ([]*ContestRegistration, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContestRegistration, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContestRegistrationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContestRegistrationCreateBulk) SaveX(ctx context.Context) []*ContestRegistration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContestRegistrationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContestRegistrationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContestRegistration.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContestRegistrationUpsert) {
//			SetContestID(v+v).
//		}).
//		Exec(ctx)
func (_c *ContestRegistrationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ContestRegistrationUpsertBulk {
	_c.conflict = opts
	return &ContestRegistrationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContestRegistration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContestRegistrationCreateBulk) OnConflictColumns(columns ...string) *ContestRegistrationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContestRegistrationUpsertBulk{
		create: _c,
	}
}

// ContestRegistrationUpsertBulk is the builder for "upsert"-ing
// a bulk of ContestRegistration nodes.
type ContestRegistrationUpsertBulk struct {
	create *ContestRegistrationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ContestRegistration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContestRegistrationUpsertBulk) UpdateNewValues() *ContestRegistrationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContestRegistration.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ContestRegistrationUpsertBulk) Ignore() *ContestRegistrationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContestRegistrationUpsertBulk) DoNothing() *ContestRegistrationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContestRegistrationCreateBulk.OnConflict
// documentation for more info.
func (u *ContestRegistrationUpsertBulk) Update(set func(*ContestRegistrationUpsert)) *ContestRegistrationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContestRegistrationUpsert{UpdateSet: update})
	}))
	return u
}

// SetContestID sets the "contest_id" field.
func (u *ContestRegistrationUpsertBulk) SetContestID(v int) *ContestRegistrationUpsertBulk {
	return u.Update(func(s *ContestRegistrationUpsert) {
		s.SetContestID(v)
	})
}

// UpdateContestID sets the "contest_id" field to the value that was provided on create.
func (u *ContestRegistrationUpsertBulk) UpdateContestID() *ContestRegistrationUpsertBulk {
	return u.Update(func(s *ContestRegistrationUpsert) {
		s.UpdateContestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ContestRegistrationUpsertBulk) SetUserID(v int) *ContestRegistrationUpsertBulk {
	return u.Update(func(s *ContestRegistrationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ContestRegistrationUpsertBulk) UpdateUserID() *ContestRegistrationUpsertBulk {
	return u.Update(func(s *ContestRegistrationUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *ContestRegistrationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("generate: OnConflict was set for builder %d. Set it on the ContestRegistrationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for ContestRegistrationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContestRegistrationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
