// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/huynhanx03/judgify/internal/ent/generate/level"
	"github.com/huynhanx03/judgify/internal/ent/generate/predicate"
	"github.com/huynhanx03/judgify/internal/ent/generate/userstats"
)

// LevelUpdate is the builder for updating Level entities.
type LevelUpdate struct {
	config
	hooks     []Hook
	mutation  *LevelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the LevelUpdate builder.
func (_u *LevelUpdate) Where(ps ...predicate.Level) *LevelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LevelUpdate) SetUpdatedAt(v time.Time) *LevelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *LevelUpdate) SetDeletedAt(v time.Time) *LevelUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *LevelUpdate) SetNillableDeletedAt(v *time.Time) *LevelUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *LevelUpdate) ClearDeletedAt() *LevelUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *LevelUpdate) SetDeletedBy(v int) *LevelUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *LevelUpdate) SetNillableDeletedBy(v *int) *LevelUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *LevelUpdate) AddDeletedBy(v int) *LevelUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *LevelUpdate) ClearDeletedBy() *LevelUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *LevelUpdate) SetName(v string) *LevelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LevelUpdate) SetNillableName(v *string) *LevelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetOrder sets the "order" field.
func (_u *LevelUpdate) SetOrder(v int) *LevelUpdate {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *LevelUpdate) SetNillableOrder(v *int) *LevelUpdate {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *LevelUpdate) AddOrder(v int) *LevelUpdate {
	_u.mutation.AddOrder(v)
	return _u
}

// SetMinExp sets the "min_exp" field.
func (_u *LevelUpdate) SetMinExp(v int64) *LevelUpdate {
	_u.mutation.ResetMinExp()
	_u.mutation.SetMinExp(v)
	return _u
}

// SetNillableMinExp sets the "min_exp" field if the given value is not nil.
func (_u *LevelUpdate) SetNillableMinExp(v *int64) *LevelUpdate {
	if v != nil {
		_u.SetMinExp(*v)
	}
	return _u
}

// AddMinExp adds value to the "min_exp" field.
func (_u *LevelUpdate) AddMinExp(v int64) *LevelUpdate {
	_u.mutation.AddMinExp(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *LevelUpdate) SetDescription(v string) *LevelUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LevelUpdate) SetNillableDescription(v *string) *LevelUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *LevelUpdate) ClearDescription() *LevelUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// AddUserStatIDs adds the "user_stats" edge to the UserStats entity by IDs.
func (_u *LevelUpdate) AddUserStatIDs(ids ...int) *LevelUpdate {
	_u.mutation.AddUserStatIDs(ids...)
	return _u
}

// AddUserStats adds the "user_stats" edges to the UserStats entity.
func (_u *LevelUpdate) AddUserStats(v ...*UserStats) *LevelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserStatIDs(ids...)
}

// Mutation returns the LevelMutation object of the builder.
func (_u *LevelUpdate) Mutation() *LevelMutation {
	return _u.mutation
}

// ClearUserStats clears all "user_stats" edges to the UserStats entity.
func (_u *LevelUpdate) ClearUserStats() *LevelUpdate {
	_u.mutation.ClearUserStats()
	return _u
}

// RemoveUserStatIDs removes the "user_stats" edge to UserStats entities by IDs.
func (_u *LevelUpdate) RemoveUserStatIDs(ids ...int) *LevelUpdate {
	_u.mutation.RemoveUserStatIDs(ids...)
	return _u
}

// RemoveUserStats removes "user_stats" edges to UserStats entities.
func (_u *LevelUpdate) RemoveUserStats(v ...*UserStats) *LevelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserStatIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LevelUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LevelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LevelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LevelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LevelUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if level.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("generate: uninitialized level.UpdateDefaultUpdatedAt (forgotten import generate/runtime?)")
		}
		v := level.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *LevelUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := level.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`generate: validator failed for field "Level.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Order(); ok {
		if err := level.OrderValidator(v); err != nil {
			return &ValidationError{Name: "order", err: fmt.Errorf(`generate: validator failed for field "Level.order": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MinExp(); ok {
		if err := level.MinExpValidator(v); err != nil {
			return &ValidationError{Name: "min_exp", err: fmt.Errorf(`generate: validator failed for field "Level.min_exp": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := level.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`generate: validator failed for field "Level.description": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LevelUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LevelUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LevelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(level.Table, level.Columns, sqlgraph.NewFieldSpec(level.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(level.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(level.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(level.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(level.FieldDeletedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(level.FieldDeletedBy, field.TypeInt, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(level.FieldDeletedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(level.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(level.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(level.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MinExp(); ok {
		_spec.SetField(level.FieldMinExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMinExp(); ok {
		_spec.AddField(level.FieldMinExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(level.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(level.FieldDescription, field.TypeString)
	}
	if _u.mutation.UserStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   level.UserStatsTable,
			Columns: []string{level.UserStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserStatsIDs(); len(nodes) > 0 && !_u.mutation.UserStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   level.UserStatsTable,
			Columns: []string{level.UserStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   level.UserStatsTable,
			Columns: []string{level.UserStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{level.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LevelUpdateOne is the builder for updating a single Level entity.
type LevelUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *LevelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LevelUpdateOne) SetUpdatedAt(v time.Time) *LevelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *LevelUpdateOne) SetDeletedAt(v time.Time) *LevelUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *LevelUpdateOne) SetNillableDeletedAt(v *time.Time) *LevelUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *LevelUpdateOne) ClearDeletedAt() *LevelUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *LevelUpdateOne) SetDeletedBy(v int) *LevelUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *LevelUpdateOne) SetNillableDeletedBy(v *int) *LevelUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *LevelUpdateOne) AddDeletedBy(v int) *LevelUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *LevelUpdateOne) ClearDeletedBy() *LevelUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *LevelUpdateOne) SetName(v string) *LevelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LevelUpdateOne) SetNillableName(v *string) *LevelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetOrder sets the "order" field.
func (_u *LevelUpdateOne) SetOrder(v int) *LevelUpdateOne {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *LevelUpdateOne) SetNillableOrder(v *int) *LevelUpdateOne {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *LevelUpdateOne) AddOrder(v int) *LevelUpdateOne {
	_u.mutation.AddOrder(v)
	return _u
}

// SetMinExp sets the "min_exp" field.
func (_u *LevelUpdateOne) SetMinExp(v int64) *LevelUpdateOne {
	_u.mutation.ResetMinExp()
	_u.mutation.SetMinExp(v)
	return _u
}

// SetNillableMinExp sets the "min_exp" field if the given value is not nil.
func (_u *LevelUpdateOne) SetNillableMinExp(v *int64) *LevelUpdateOne {
	if v != nil {
		_u.SetMinExp(*v)
	}
	return _u
}

// AddMinExp adds value to the "min_exp" field.
func (_u *LevelUpdateOne) AddMinExp(v int64) *LevelUpdateOne {
	_u.mutation.AddMinExp(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *LevelUpdateOne) SetDescription(v string) *LevelUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LevelUpdateOne) SetNillableDescription(v *string) *LevelUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *LevelUpdateOne) ClearDescription() *LevelUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// AddUserStatIDs adds the "user_stats" edge to the UserStats entity by IDs.
func (_u *LevelUpdateOne) AddUserStatIDs(ids ...int) *LevelUpdateOne {
	_u.mutation.AddUserStatIDs(ids...)
	return _u
}

// AddUserStats adds the "user_stats" edges to the UserStats entity.
func (_u *LevelUpdateOne) AddUserStats(v ...*UserStats) *LevelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserStatIDs(ids...)
}

// Mutation returns the LevelMutation object of the builder.
func (_u *LevelUpdateOne) Mutation() *LevelMutation {
	return _u.mutation
}

// ClearUserStats clears all "user_stats" edges to the UserStats entity.
func (_u *LevelUpdateOne) ClearUserStats() *LevelUpdateOne {
	_u.mutation.ClearUserStats()
	return _u
}

// RemoveUserStatIDs removes the "user_stats" edge to UserStats entities by IDs.
func (_u *LevelUpdateOne) RemoveUserStatIDs(ids ...int) *LevelUpdateOne {
	_u.mutation.RemoveUserStatIDs(ids...)
	return _u
}

// RemoveUserStats removes "user_stats" edges to UserStats entities.
func (_u *LevelUpdateOne) RemoveUserStats(v ...*UserStats) *LevelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserStatIDs(ids...)
}

// Where appends a list predicates to the LevelUpdate builder.
func (_u *LevelUpdateOne) Where(ps ...predicate.Level) *LevelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LevelUpdateOne) Select(field string, fields ...string) *LevelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Level entity.
func (_u *LevelUpdateOne) Save(ctx context.Context) (*Level, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LevelUpdateOne) SaveX(ctx context.Context) *Level {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LevelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LevelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LevelUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if level.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("generate: uninitialized level.UpdateDefaultUpdatedAt (forgotten import generate/runtime?)")
		}
		v := level.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *LevelUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := level.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`generate: validator failed for field "Level.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Order(); ok {
		if err := level.OrderValidator(v); err != nil {
			return &ValidationError{Name: "order", err: fmt.Errorf(`generate: validator failed for field "Level.order": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MinExp(); ok {
		if err := level.MinExpValidator(v); err != nil {
			return &ValidationError{Name: "min_exp", err: fmt.Errorf(`generate: validator failed for field "Level.min_exp": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := level.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`generate: validator failed for field "Level.description": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LevelUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LevelUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LevelUpdateOne) sqlSave(ctx context.Context) (_node *Level, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(level.Table, level.Columns, sqlgraph.NewFieldSpec(level.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`generate: missing "Level.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, level.FieldID)
		for _, f := range fields {
			if !level.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("generate: invalid field %q for query", f)}
			}
			if f != level.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(level.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(level.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(level.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(level.FieldDeletedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(level.FieldDeletedBy, field.TypeInt, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(level.FieldDeletedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(level.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(level.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(level.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MinExp(); ok {
		_spec.SetField(level.FieldMinExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMinExp(); ok {
		_spec.AddField(level.FieldMinExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(level.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(level.FieldDescription, field.TypeString)
	}
	if _u.mutation.UserStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   level.UserStatsTable,
			Columns: []string{level.UserStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserStatsIDs(); len(nodes) > 0 && !_u.mutation.UserStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   level.UserStatsTable,
			Columns: []string{level.UserStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   level.UserStatsTable,
			Columns: []string{level.UserStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Level{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{level.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
