// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/huynhanx03/judgify/internal/ent/generate/difficulty"
	"github.com/huynhanx03/judgify/internal/ent/generate/material"
	"github.com/huynhanx03/judgify/internal/ent/generate/materialcategory"
	"github.com/huynhanx03/judgify/internal/ent/generate/tag"
	"github.com/huynhanx03/judgify/internal/ent/generate/user"
)

// MaterialCreate is the builder for creating a Material entity.
type MaterialCreate struct {
	config
	mutation *MaterialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MaterialCreate) SetCreatedAt(v time.Time) *MaterialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MaterialCreate) SetNillableCreatedAt(v *time.Time) *MaterialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MaterialCreate) SetUpdatedAt(v time.Time) *MaterialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MaterialCreate) SetNillableUpdatedAt(v *time.Time) *MaterialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *MaterialCreate) SetDeletedAt(v time.Time) *MaterialCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *MaterialCreate) SetNillableDeletedAt(v *time.Time) *MaterialCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *MaterialCreate) SetDeletedBy(v int) *MaterialCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *MaterialCreate) SetNillableDeletedBy(v *int) *MaterialCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *MaterialCreate) SetTitle(v string) *MaterialCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *MaterialCreate) SetDescription(v string) *MaterialCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MaterialCreate) SetNillableDescription(v *string) *MaterialCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *MaterialCreate) SetContent(v string) *MaterialCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *MaterialCreate) SetNillableContent(v *string) *MaterialCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetDifficultyID sets the "difficulty_id" field.
func (_c *MaterialCreate) SetDifficultyID(v int) *MaterialCreate {
	_c.mutation.SetDifficultyID(v)
	return _c
}

// SetAuthorID sets the "author_id" field.
func (_c *MaterialCreate) SetAuthorID(v int) *MaterialCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *MaterialCreate) SetCategoryID(v int) *MaterialCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MaterialCreate) SetStatus(v material.Status) *MaterialCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MaterialCreate) SetNillableStatus(v *material.Status) *MaterialCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *MaterialCreate) SetVisibility(v material.Visibility) *MaterialCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_c *MaterialCreate) SetNillableVisibility(v *material.Visibility) *MaterialCreate {
	if v != nil {
		_c.SetVisibility(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *MaterialCreate) SetGroupID(v int) *MaterialCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *MaterialCreate) SetNillableGroupID(v *int) *MaterialCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *MaterialCreate) SetViewCount(v int) *MaterialCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *MaterialCreate) SetNillableViewCount(v *int) *MaterialCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetEstimatedReadTime sets the "estimated_read_time" field.
func (_c *MaterialCreate) SetEstimatedReadTime(v int) *MaterialCreate {
	_c.mutation.SetEstimatedReadTime(v)
	return _c
}

// SetNillableEstimatedReadTime sets the "estimated_read_time" field if the given value is not nil.
func (_c *MaterialCreate) SetNillableEstimatedReadTime(v *int) *MaterialCreate {
	if v != nil {
		_c.SetEstimatedReadTime(*v)
	}
	return _c
}

// SetCategory sets the "category" edge to the MaterialCategory entity.
func (_c *MaterialCreate) SetCategory(v *MaterialCategory) *MaterialCreate {
	return _c.SetCategoryID(v.ID)
}

// SetAuthor sets the "author" edge to the User entity.
func (_c *MaterialCreate) SetAuthor(v *User) *MaterialCreate {
	return _c.SetAuthorID(v.ID)
}

// SetDifficulty sets the "difficulty" edge to the Difficulty entity.
func (_c *MaterialCreate) SetDifficulty(v *Difficulty) *MaterialCreate {
	return _c.SetDifficultyID(v.ID)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_c *MaterialCreate) AddTagIDs(ids ...int) *MaterialCreate {
	_c.mutation.AddTagIDs(ids...)
	return _c
}

// AddTags adds the "tags" edges to the Tag entity.
func (_c *MaterialCreate) AddTags(v ...*Tag) *MaterialCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTagIDs(ids...)
}

// Mutation returns the MaterialMutation object of the builder.
func (_c *MaterialCreate) Mutation() *MaterialMutation {
	return _c.mutation
}

// Save creates the Material in the database.
func (_c *MaterialCreate) Save(ctx context.Context) (*Material, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MaterialCreate) SaveX(ctx context.Context) *Material {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MaterialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MaterialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MaterialCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if material.DefaultCreatedAt == nil {
			return fmt.Errorf("generate: uninitialized material.DefaultCreatedAt (forgotten import generate/runtime?)")
		}
		v := material.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if material.DefaultUpdatedAt == nil {
			return fmt.Errorf("generate: uninitialized material.DefaultUpdatedAt (forgotten import generate/runtime?)")
		}
		v := material.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := material.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		v := material.DefaultVisibility
		_c.mutation.SetVisibility(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := material.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.EstimatedReadTime(); !ok {
		v := material.DefaultEstimatedReadTime
		_c.mutation.SetEstimatedReadTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *MaterialCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`generate: missing required field "Material.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`generate: missing required field "Material.updated_at"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`generate: missing required field "Material.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := material.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`generate: validator failed for field "Material.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := material.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`generate: validator failed for field "Material.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DifficultyID(); !ok {
		return &ValidationError{Name: "difficulty_id", err: errors.New(`generate: missing required field "Material.difficulty_id"`)}
	}
	if _, ok := _c.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`generate: missing required field "Material.author_id"`)}
	}
	if _, ok := _c.mutation.CategoryID(); !ok {
		return &ValidationError{Name: "category_id", err: errors.New(`generate: missing required field "Material.category_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`generate: missing required field "Material.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := material.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`generate: validator failed for field "Material.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`generate: missing required field "Material.visibility"`)}
	}
	if v, ok := _c.mutation.Visibility(); ok {
		if err := material.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`generate: validator failed for field "Material.visibility": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`generate: missing required field "Material.view_count"`)}
	}
	if v, ok := _c.mutation.ViewCount(); ok {
		if err := material.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`generate: validator failed for field "Material.view_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EstimatedReadTime(); !ok {
		return &ValidationError{Name: "estimated_read_time", err: errors.New(`generate: missing required field "Material.estimated_read_time"`)}
	}
	if v, ok := _c.mutation.EstimatedReadTime(); ok {
		if err := material.EstimatedReadTimeValidator(v); err != nil {
			return &ValidationError{Name: "estimated_read_time", err: fmt.Errorf(`generate: validator failed for field "Material.estimated_read_time": %w`, err)}
		}
	}
	if len(_c.mutation.CategoryIDs()) == 0 {
		return &ValidationError{Name: "category", err: errors.New(`generate: missing required edge "Material.category"`)}
	}
	if len(_c.mutation.AuthorIDs()) == 0 {
		return &ValidationError{Name: "author", err: errors.New(`generate: missing required edge "Material.author"`)}
	}
	if len(_c.mutation.DifficultyIDs()) == 0 {
		return &ValidationError{Name: "difficulty", err: errors.New(`generate: missing required edge "Material.difficulty"`)}
	}
	return nil
}

func (_c *MaterialCreate) sqlSave(ctx context.Context) (*Material, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MaterialCreate) createSpec() (*Material, *sqlgraph.CreateSpec) {
	var (
		_node = &Material{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(material.Table, sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(material.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(material.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(material.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(material.FieldDeletedBy, field.TypeInt, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(material.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(material.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(material.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(material.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(material.FieldVisibility, field.TypeEnum, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(material.FieldGroupID, field.TypeInt, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(material.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.EstimatedReadTime(); ok {
		_spec.SetField(material.FieldEstimatedReadTime, field.TypeInt, value)
		_node.EstimatedReadTime = value
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   material.CategoryTable,
			Columns: []string{material.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(materialcategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   material.AuthorTable,
			Columns: []string{material.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AuthorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DifficultyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   material.DifficultyTable,
			Columns: []string{material.DifficultyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(difficulty.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DifficultyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   material.TagsTable,
			Columns: material.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Material.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MaterialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MaterialCreate) OnConflict(opts ...sql.ConflictOption) *MaterialUpsertOne {
	_c.conflict = opts
	return &MaterialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Material.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MaterialCreate) OnConflictColumns(columns ...string) *MaterialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MaterialUpsertOne{
		create: _c,
	}
}

type (
	// MaterialUpsertOne is the builder for "upsert"-ing
	//  one Material node.
	MaterialUpsertOne struct {
		create *MaterialCreate
	}

	// MaterialUpsert is the "OnConflict" setter.
	MaterialUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MaterialUpsert) SetUpdatedAt(v time.Time) *MaterialUpsert {
	u.Set(material.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateUpdatedAt() *MaterialUpsert {
	u.SetExcluded(material.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MaterialUpsert) SetDeletedAt(v time.Time) *MaterialUpsert {
	u.Set(material.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateDeletedAt() *MaterialUpsert {
	u.SetExcluded(material.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *MaterialUpsert) ClearDeletedAt() *MaterialUpsert {
	u.SetNull(material.FieldDeletedAt)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *MaterialUpsert) SetDeletedBy(v int) *MaterialUpsert {
	u.Set(material.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateDeletedBy() *MaterialUpsert {
	u.SetExcluded(material.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *MaterialUpsert) AddDeletedBy(v int) *MaterialUpsert {
	u.Add(material.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *MaterialUpsert) ClearDeletedBy() *MaterialUpsert {
	u.SetNull(material.FieldDeletedBy)
	return u
}

// SetTitle sets the "title" field.
func (u *MaterialUpsert) SetTitle(v string) *MaterialUpsert {
	u.Set(material.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateTitle() *MaterialUpsert {
	u.SetExcluded(material.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *MaterialUpsert) SetDescription(v string) *MaterialUpsert {
	u.Set(material.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateDescription() *MaterialUpsert {
	u.SetExcluded(material.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *MaterialUpsert) ClearDescription() *MaterialUpsert {
	u.SetNull(material.FieldDescription)
	return u
}

// SetContent sets the "content" field.
func (u *MaterialUpsert) SetContent(v string) *MaterialUpsert {
	u.Set(material.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateContent() *MaterialUpsert {
	u.SetExcluded(material.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *MaterialUpsert) ClearContent() *MaterialUpsert {
	u.SetNull(material.FieldContent)
	return u
}

// SetDifficultyID sets the "difficulty_id" field.
func (u *MaterialUpsert) SetDifficultyID(v int) *MaterialUpsert {
	u.Set(material.FieldDifficultyID, v)
	return u
}

// UpdateDifficultyID sets the "difficulty_id" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateDifficultyID() *MaterialUpsert {
	u.SetExcluded(material.FieldDifficultyID)
	return u
}

// SetAuthorID sets the "author_id" field.
func (u *MaterialUpsert) SetAuthorID(v int) *MaterialUpsert {
	u.Set(material.FieldAuthorID, v)
	return u
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateAuthorID() *MaterialUpsert {
	u.SetExcluded(material.FieldAuthorID)
	return u
}

// SetCategoryID sets the "category_id" field.
func (u *MaterialUpsert) SetCategoryID(v int) *MaterialUpsert {
	u.Set(material.FieldCategoryID, v)
	return u
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateCategoryID() *MaterialUpsert {
	u.SetExcluded(material.FieldCategoryID)
	return u
}

// SetStatus sets the "status" field.
func (u *MaterialUpsert) SetStatus(v material.Status) *MaterialUpsert {
	u.Set(material.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateStatus() *MaterialUpsert {
	u.SetExcluded(material.FieldStatus)
	return u
}

// SetVisibility sets the "visibility" field.
func (u *MaterialUpsert) SetVisibility(v material.Visibility) *MaterialUpsert {
	u.Set(material.FieldVisibility, v)
	return u
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateVisibility() *MaterialUpsert {
	u.SetExcluded(material.FieldVisibility)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *MaterialUpsert) SetGroupID(v int) *MaterialUpsert {
	u.Set(material.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateGroupID() *MaterialUpsert {
	u.SetExcluded(material.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *MaterialUpsert) AddGroupID(v int) *MaterialUpsert {
	u.Add(material.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *MaterialUpsert) ClearGroupID() *MaterialUpsert {
	u.SetNull(material.FieldGroupID)
	return u
}

// SetViewCount sets the "view_count" field.
func (u *MaterialUpsert) SetViewCount(v int) *MaterialUpsert {
	u.Set(material.FieldViewCount, v)
	return u
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateViewCount() *MaterialUpsert {
	u.SetExcluded(material.FieldViewCount)
	return u
}

// AddViewCount adds v to the "view_count" field.
func (u *MaterialUpsert) AddViewCount(v int) *MaterialUpsert {
	u.Add(material.FieldViewCount, v)
	return u
}

// SetEstimatedReadTime sets the "estimated_read_time" field.
func (u *MaterialUpsert) SetEstimatedReadTime(v int) *MaterialUpsert {
	u.Set(material.FieldEstimatedReadTime, v)
	return u
}

// UpdateEstimatedReadTime sets the "estimated_read_time" field to the value that was provided on create.
func (u *MaterialUpsert) UpdateEstimatedReadTime() *MaterialUpsert {
	u.SetExcluded(material.FieldEstimatedReadTime)
	return u
}

// AddEstimatedReadTime adds v to the "estimated_read_time" field.
func (u *MaterialUpsert) AddEstimatedReadTime(v int) *MaterialUpsert {
	u.Add(material.FieldEstimatedReadTime, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Material.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MaterialUpsertOne) UpdateNewValues() *MaterialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(material.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Material.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MaterialUpsertOne) Ignore() *MaterialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MaterialUpsertOne) DoNothing() *MaterialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MaterialCreate.OnConflict
// documentation for more info.
func (u *MaterialUpsertOne) Update(set func(*MaterialUpsert)) *MaterialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MaterialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MaterialUpsertOne) SetUpdatedAt(v time.Time) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateUpdatedAt() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MaterialUpsertOne) SetDeletedAt(v time.Time) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateDeletedAt() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *MaterialUpsertOne) ClearDeletedAt() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *MaterialUpsertOne) SetDeletedBy(v int) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *MaterialUpsertOne) AddDeletedBy(v int) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateDeletedBy() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *MaterialUpsertOne) ClearDeletedBy() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.ClearDeletedBy()
	})
}

// SetTitle sets the "title" field.
func (u *MaterialUpsertOne) SetTitle(v string) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateTitle() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *MaterialUpsertOne) SetDescription(v string) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateDescription() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *MaterialUpsertOne) ClearDescription() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.ClearDescription()
	})
}

// SetContent sets the "content" field.
func (u *MaterialUpsertOne) SetContent(v string) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateContent() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *MaterialUpsertOne) ClearContent() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.ClearContent()
	})
}

// SetDifficultyID sets the "difficulty_id" field.
func (u *MaterialUpsertOne) SetDifficultyID(v int) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetDifficultyID(v)
	})
}

// UpdateDifficultyID sets the "difficulty_id" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateDifficultyID() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateDifficultyID()
	})
}

// SetAuthorID sets the "author_id" field.
func (u *MaterialUpsertOne) SetAuthorID(v int) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetAuthorID(v)
	})
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateAuthorID() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateAuthorID()
	})
}

// SetCategoryID sets the "category_id" field.
func (u *MaterialUpsertOne) SetCategoryID(v int) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetCategoryID(v)
	})
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateCategoryID() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateCategoryID()
	})
}

// SetStatus sets the "status" field.
func (u *MaterialUpsertOne) SetStatus(v material.Status) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateStatus() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateStatus()
	})
}

// SetVisibility sets the "visibility" field.
func (u *MaterialUpsertOne) SetVisibility(v material.Visibility) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateVisibility() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateVisibility()
	})
}

// SetGroupID sets the "group_id" field.
func (u *MaterialUpsertOne) SetGroupID(v int) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *MaterialUpsertOne) AddGroupID(v int) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateGroupID() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *MaterialUpsertOne) ClearGroupID() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.ClearGroupID()
	})
}

// SetViewCount sets the "view_count" field.
func (u *MaterialUpsertOne) SetViewCount(v int) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetViewCount(v)
	})
}

// AddViewCount adds v to the "view_count" field.
func (u *MaterialUpsertOne) AddViewCount(v int) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.AddViewCount(v)
	})
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateViewCount() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateViewCount()
	})
}

// SetEstimatedReadTime sets the "estimated_read_time" field.
func (u *MaterialUpsertOne) SetEstimatedReadTime(v int) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.SetEstimatedReadTime(v)
	})
}

// AddEstimatedReadTime adds v to the "estimated_read_time" field.
func (u *MaterialUpsertOne) AddEstimatedReadTime(v int) *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.AddEstimatedReadTime(v)
	})
}

// UpdateEstimatedReadTime sets the "estimated_read_time" field to the value that was provided on create.
func (u *MaterialUpsertOne) UpdateEstimatedReadTime() *MaterialUpsertOne {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateEstimatedReadTime()
	})
}

// Exec executes the query.
func (u *MaterialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for MaterialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MaterialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MaterialUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MaterialUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (c *MaterialCreate) SetID(id int) *MaterialCreate {
	c.mutation.id = &id
	return c
}

// MaterialCreateBulk is the builder for creating many Material entities in bulk.
type MaterialCreateBulk struct {
	config
	err      error
	builders []*MaterialCreate
	conflict []sql.ConflictOption
}

// Save creates the Material entities in the database.
func (_c *MaterialCreateBulk) Save(ctx context.Context) ([]*Material, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Material, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MaterialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MaterialCreateBulk) SaveX(ctx context.Context) []*Material {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MaterialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MaterialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Material.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MaterialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MaterialCreateBulk) OnConflict(opts ...sql.ConflictOption) *MaterialUpsertBulk {
	_c.conflict = opts
	return &MaterialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Material.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MaterialCreateBulk) OnConflictColumns(columns ...string) *MaterialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MaterialUpsertBulk{
		create: _c,
	}
}

// MaterialUpsertBulk is the builder for "upsert"-ing
// a bulk of Material nodes.
type MaterialUpsertBulk struct {
	create *MaterialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Material.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MaterialUpsertBulk) UpdateNewValues() *MaterialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(material.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Material.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MaterialUpsertBulk) Ignore() *MaterialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MaterialUpsertBulk) DoNothing() *MaterialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MaterialCreateBulk.OnConflict
// documentation for more info.
func (u *MaterialUpsertBulk) Update(set func(*MaterialUpsert)) *MaterialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MaterialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MaterialUpsertBulk) SetUpdatedAt(v time.Time) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateUpdatedAt() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MaterialUpsertBulk) SetDeletedAt(v time.Time) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateDeletedAt() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *MaterialUpsertBulk) ClearDeletedAt() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *MaterialUpsertBulk) SetDeletedBy(v int) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *MaterialUpsertBulk) AddDeletedBy(v int) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateDeletedBy() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *MaterialUpsertBulk) ClearDeletedBy() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.ClearDeletedBy()
	})
}

// SetTitle sets the "title" field.
func (u *MaterialUpsertBulk) SetTitle(v string) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateTitle() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *MaterialUpsertBulk) SetDescription(v string) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateDescription() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *MaterialUpsertBulk) ClearDescription() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.ClearDescription()
	})
}

// SetContent sets the "content" field.
func (u *MaterialUpsertBulk) SetContent(v string) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateContent() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *MaterialUpsertBulk) ClearContent() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.ClearContent()
	})
}

// SetDifficultyID sets the "difficulty_id" field.
func (u *MaterialUpsertBulk) SetDifficultyID(v int) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetDifficultyID(v)
	})
}

// UpdateDifficultyID sets the "difficulty_id" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateDifficultyID() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateDifficultyID()
	})
}

// SetAuthorID sets the "author_id" field.
func (u *MaterialUpsertBulk) SetAuthorID(v int) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetAuthorID(v)
	})
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateAuthorID() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateAuthorID()
	})
}

// SetCategoryID sets the "category_id" field.
func (u *MaterialUpsertBulk) SetCategoryID(v int) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetCategoryID(v)
	})
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateCategoryID() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateCategoryID()
	})
}

// SetStatus sets the "status" field.
func (u *MaterialUpsertBulk) SetStatus(v material.Status) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateStatus() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateStatus()
	})
}

// SetVisibility sets the "visibility" field.
func (u *MaterialUpsertBulk) SetVisibility(v material.Visibility) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateVisibility() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateVisibility()
	})
}

// SetGroupID sets the "group_id" field.
func (u *MaterialUpsertBulk) SetGroupID(v int) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *MaterialUpsertBulk) AddGroupID(v int) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateGroupID() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *MaterialUpsertBulk) ClearGroupID() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.ClearGroupID()
	})
}

// SetViewCount sets the "view_count" field.
func (u *MaterialUpsertBulk) SetViewCount(v int) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetViewCount(v)
	})
}

// AddViewCount adds v to the "view_count" field.
func (u *MaterialUpsertBulk) AddViewCount(v int) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.AddViewCount(v)
	})
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateViewCount() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateViewCount()
	})
}

// SetEstimatedReadTime sets the "estimated_read_time" field.
func (u *MaterialUpsertBulk) SetEstimatedReadTime(v int) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.SetEstimatedReadTime(v)
	})
}

// AddEstimatedReadTime adds v to the "estimated_read_time" field.
func (u *MaterialUpsertBulk) AddEstimatedReadTime(v int) *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.AddEstimatedReadTime(v)
	})
}

// UpdateEstimatedReadTime sets the "estimated_read_time" field to the value that was provided on create.
func (u *MaterialUpsertBulk) UpdateEstimatedReadTime() *MaterialUpsertBulk {
	return u.Update(func(s *MaterialUpsert) {
		s.UpdateEstimatedReadTime()
	})
}

// Exec executes the query.
func (u *MaterialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("generate: OnConflict was set for builder %d. Set it on the MaterialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for MaterialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MaterialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
