// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/huynhanx03/judgify/internal/ent/generate/predicate"
	"github.com/huynhanx03/judgify/internal/ent/generate/rarity"
	"github.com/huynhanx03/judgify/internal/ent/generate/trait"
)

// RarityQuery is the builder for querying Rarity entities.
type RarityQuery struct {
	config
	ctx        *QueryContext
	order      []rarity.OrderOption
	inters     []Interceptor
	predicates []predicate.Rarity
	withTraits *TraitQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RarityQuery builder.
func (_q *RarityQuery) Where(ps ...predicate.Rarity) *RarityQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RarityQuery) Limit(limit int) *RarityQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RarityQuery) Offset(offset int) *RarityQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RarityQuery) Unique(unique bool) *RarityQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RarityQuery) Order(o ...rarity.OrderOption) *RarityQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTraits chains the current query on the "traits" edge.
func (_q *RarityQuery) QueryTraits() *TraitQuery {
	query := (&TraitClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rarity.Table, rarity.FieldID, selector),
			sqlgraph.To(trait.Table, trait.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, rarity.TraitsTable, rarity.TraitsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Rarity entity from the query.
// Returns a *NotFoundError when no Rarity was found.
func (_q *RarityQuery) First(ctx context.Context) (*Rarity, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rarity.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RarityQuery) FirstX(ctx context.Context) *Rarity {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Rarity ID from the query.
// Returns a *NotFoundError when no Rarity ID was found.
func (_q *RarityQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rarity.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RarityQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Rarity entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Rarity entity is found.
// Returns a *NotFoundError when no Rarity entities are found.
func (_q *RarityQuery) Only(ctx context.Context) (*Rarity, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rarity.Label}
	default:
		return nil, &NotSingularError{rarity.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RarityQuery) OnlyX(ctx context.Context) *Rarity {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Rarity ID in the query.
// Returns a *NotSingularError when more than one Rarity ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RarityQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rarity.Label}
	default:
		err = &NotSingularError{rarity.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RarityQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Rarities.
func (_q *RarityQuery) All(ctx context.Context) ([]*Rarity, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Rarity, *RarityQuery]()
	return withInterceptors[[]*Rarity](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RarityQuery) AllX(ctx context.Context) []*Rarity {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Rarity IDs.
func (_q *RarityQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(rarity.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RarityQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RarityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RarityQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RarityQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RarityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("generate: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RarityQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RarityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RarityQuery) Clone() *RarityQuery {
	if _q == nil {
		return nil
	}
	return &RarityQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]rarity.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.Rarity{}, _q.predicates...),
		withTraits: _q.withTraits.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithTraits tells the query-builder to eager-load the nodes that are connected to
// the "traits" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RarityQuery) WithTraits(opts ...func(*TraitQuery)) *RarityQuery {
	query := (&TraitClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTraits = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Rarity.Query().
//		GroupBy(rarity.FieldCreatedAt).
//		Aggregate(generate.Count()).
//		Scan(ctx, &v)
func (_q *RarityQuery) GroupBy(field string, fields ...string) *RarityGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RarityGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = rarity.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Rarity.Query().
//		Select(rarity.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *RarityQuery) Select(fields ...string) *RaritySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RaritySelect{RarityQuery: _q}
	sbuild.label = rarity.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RaritySelect configured with the given aggregations.
func (_q *RarityQuery) Aggregate(fns ...AggregateFunc) *RaritySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RarityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("generate: uninitialized interceptor (forgotten import generate/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !rarity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("generate: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RarityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Rarity, error) {
	var (
		nodes       = []*Rarity{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withTraits != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Rarity).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Rarity{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTraits; query != nil {
		if err := _q.loadTraits(ctx, query, nodes,
			func(n *Rarity) { n.Edges.Traits = []*Trait{} },
			func(n *Rarity, e *Trait) {
				n.Edges.Traits = append(n.Edges.Traits, e)
				if !e.Edges.loadedTypes[0] {
					e.Edges.Rarity = n
				}
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RarityQuery) loadTraits(ctx context.Context, query *TraitQuery, nodes []*Rarity, init func(*Rarity), assign func(*Rarity, *Trait)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Rarity)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(trait.FieldRarityID)
	}
	query.Where(predicate.Trait(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(rarity.TraitsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RarityID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "rarity_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *RarityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RarityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rarity.Table, rarity.Columns, sqlgraph.NewFieldSpec(rarity.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rarity.FieldID)
		for i := range fields {
			if fields[i] != rarity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RarityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(rarity.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = rarity.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *RarityQuery) ForUpdate(opts ...sql.LockOption) *RarityQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *RarityQuery) ForShare(opts ...sql.LockOption) *RarityQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *RarityQuery) Modify(modifiers ...func(s *sql.Selector)) *RaritySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// RarityGroupBy is the group-by builder for Rarity entities.
type RarityGroupBy struct {
	selector
	build *RarityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RarityGroupBy) Aggregate(fns ...AggregateFunc) *RarityGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RarityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RarityQuery, *RarityGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RarityGroupBy) sqlScan(ctx context.Context, root *RarityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RaritySelect is the builder for selecting fields of Rarity entities.
type RaritySelect struct {
	*RarityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RaritySelect) Aggregate(fns ...AggregateFunc) *RaritySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RaritySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RarityQuery, *RaritySelect](ctx, _s.RarityQuery, _s, _s.inters, v)
}

func (_s *RaritySelect) sqlScan(ctx context.Context, root *RarityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *RaritySelect) Modify(modifiers ...func(s *sql.Selector)) *RaritySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
