// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/huynhanx03/judgify/internal/ent/generate/contest"
	"github.com/huynhanx03/judgify/internal/ent/generate/predicate"
	"github.com/huynhanx03/judgify/internal/ent/generate/ratinghistory"
	"github.com/huynhanx03/judgify/internal/ent/generate/user"
)

// RatingHistoryUpdate is the builder for updating RatingHistory entities.
type RatingHistoryUpdate struct {
	config
	hooks     []Hook
	mutation  *RatingHistoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RatingHistoryUpdate builder.
func (_u *RatingHistoryUpdate) Where(ps ...predicate.RatingHistory) *RatingHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RatingHistoryUpdate) SetUserID(v int) *RatingHistoryUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RatingHistoryUpdate) SetNillableUserID(v *int) *RatingHistoryUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetContestID sets the "contest_id" field.
func (_u *RatingHistoryUpdate) SetContestID(v int) *RatingHistoryUpdate {
	_u.mutation.SetContestID(v)
	return _u
}

// SetNillableContestID sets the "contest_id" field if the given value is not nil.
func (_u *RatingHistoryUpdate) SetNillableContestID(v *int) *RatingHistoryUpdate {
	if v != nil {
		_u.SetContestID(*v)
	}
	return _u
}

// SetOldRating sets the "old_rating" field.
func (_u *RatingHistoryUpdate) SetOldRating(v int) *RatingHistoryUpdate {
	_u.mutation.ResetOldRating()
	_u.mutation.SetOldRating(v)
	return _u
}

// SetNillableOldRating sets the "old_rating" field if the given value is not nil.
func (_u *RatingHistoryUpdate) SetNillableOldRating(v *int) *RatingHistoryUpdate {
	if v != nil {
		_u.SetOldRating(*v)
	}
	return _u
}

// AddOldRating adds value to the "old_rating" field.
func (_u *RatingHistoryUpdate) AddOldRating(v int) *RatingHistoryUpdate {
	_u.mutation.AddOldRating(v)
	return _u
}

// SetNewRating sets the "new_rating" field.
func (_u *RatingHistoryUpdate) SetNewRating(v int) *RatingHistoryUpdate {
	_u.mutation.ResetNewRating()
	_u.mutation.SetNewRating(v)
	return _u
}

// SetNillableNewRating sets the "new_rating" field if the given value is not nil.
func (_u *RatingHistoryUpdate) SetNillableNewRating(v *int) *RatingHistoryUpdate {
	if v != nil {
		_u.SetNewRating(*v)
	}
	return _u
}

// AddNewRating adds value to the "new_rating" field.
func (_u *RatingHistoryUpdate) AddNewRating(v int) *RatingHistoryUpdate {
	_u.mutation.AddNewRating(v)
	return _u
}

// SetRankPosition sets the "rank_position" field.
func (_u *RatingHistoryUpdate) SetRankPosition(v int) *RatingHistoryUpdate {
	_u.mutation.ResetRankPosition()
	_u.mutation.SetRankPosition(v)
	return _u
}

// SetNillableRankPosition sets the "rank_position" field if the given value is not nil.
func (_u *RatingHistoryUpdate) SetNillableRankPosition(v *int) *RatingHistoryUpdate {
	if v != nil {
		_u.SetRankPosition(*v)
	}
	return _u
}

// AddRankPosition adds value to the "rank_position" field.
func (_u *RatingHistoryUpdate) AddRankPosition(v int) *RatingHistoryUpdate {
	_u.mutation.AddRankPosition(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RatingHistoryUpdate) SetUser(v *User) *RatingHistoryUpdate {
	return _u.SetUserID(v.ID)
}

// SetContest sets the "contest" edge to the Contest entity.
func (_u *RatingHistoryUpdate) SetContest(v *Contest) *RatingHistoryUpdate {
	return _u.SetContestID(v.ID)
}

// Mutation returns the RatingHistoryMutation object of the builder.
func (_u *RatingHistoryUpdate) Mutation() *RatingHistoryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RatingHistoryUpdate) ClearUser() *RatingHistoryUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearContest clears the "contest" edge to the Contest entity.
func (_u *RatingHistoryUpdate) ClearContest() *RatingHistoryUpdate {
	_u.mutation.ClearContest()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RatingHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RatingHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RatingHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RatingHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RatingHistoryUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "RatingHistory.user"`)
	}
	if _u.mutation.ContestCleared() && len(_u.mutation.ContestIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "RatingHistory.contest"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RatingHistoryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RatingHistoryUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RatingHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ratinghistory.Table, ratinghistory.Columns, sqlgraph.NewFieldSpec(ratinghistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OldRating(); ok {
		_spec.SetField(ratinghistory.FieldOldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOldRating(); ok {
		_spec.AddField(ratinghistory.FieldOldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NewRating(); ok {
		_spec.SetField(ratinghistory.FieldNewRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNewRating(); ok {
		_spec.AddField(ratinghistory.FieldNewRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RankPosition(); ok {
		_spec.SetField(ratinghistory.FieldRankPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRankPosition(); ok {
		_spec.AddField(ratinghistory.FieldRankPosition, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ratinghistory.UserTable,
			Columns: []string{ratinghistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ratinghistory.UserTable,
			Columns: []string{ratinghistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ratinghistory.ContestTable,
			Columns: []string{ratinghistory.ContestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ratinghistory.ContestTable,
			Columns: []string{ratinghistory.ContestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ratinghistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RatingHistoryUpdateOne is the builder for updating a single RatingHistory entity.
type RatingHistoryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RatingHistoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (_u *RatingHistoryUpdateOne) SetUserID(v int) *RatingHistoryUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RatingHistoryUpdateOne) SetNillableUserID(v *int) *RatingHistoryUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetContestID sets the "contest_id" field.
func (_u *RatingHistoryUpdateOne) SetContestID(v int) *RatingHistoryUpdateOne {
	_u.mutation.SetContestID(v)
	return _u
}

// SetNillableContestID sets the "contest_id" field if the given value is not nil.
func (_u *RatingHistoryUpdateOne) SetNillableContestID(v *int) *RatingHistoryUpdateOne {
	if v != nil {
		_u.SetContestID(*v)
	}
	return _u
}

// SetOldRating sets the "old_rating" field.
func (_u *RatingHistoryUpdateOne) SetOldRating(v int) *RatingHistoryUpdateOne {
	_u.mutation.ResetOldRating()
	_u.mutation.SetOldRating(v)
	return _u
}

// SetNillableOldRating sets the "old_rating" field if the given value is not nil.
func (_u *RatingHistoryUpdateOne) SetNillableOldRating(v *int) *RatingHistoryUpdateOne {
	if v != nil {
		_u.SetOldRating(*v)
	}
	return _u
}

// AddOldRating adds value to the "old_rating" field.
func (_u *RatingHistoryUpdateOne) AddOldRating(v int) *RatingHistoryUpdateOne {
	_u.mutation.AddOldRating(v)
	return _u
}

// SetNewRating sets the "new_rating" field.
func (_u *RatingHistoryUpdateOne) SetNewRating(v int) *RatingHistoryUpdateOne {
	_u.mutation.ResetNewRating()
	_u.mutation.SetNewRating(v)
	return _u
}

// SetNillableNewRating sets the "new_rating" field if the given value is not nil.
func (_u *RatingHistoryUpdateOne) SetNillableNewRating(v *int) *RatingHistoryUpdateOne {
	if v != nil {
		_u.SetNewRating(*v)
	}
	return _u
}

// AddNewRating adds value to the "new_rating" field.
func (_u *RatingHistoryUpdateOne) AddNewRating(v int) *RatingHistoryUpdateOne {
	_u.mutation.AddNewRating(v)
	return _u
}

// SetRankPosition sets the "rank_position" field.
func (_u *RatingHistoryUpdateOne) SetRankPosition(v int) *RatingHistoryUpdateOne {
	_u.mutation.ResetRankPosition()
	_u.mutation.SetRankPosition(v)
	return _u
}

// SetNillableRankPosition sets the "rank_position" field if the given value is not nil.
func (_u *RatingHistoryUpdateOne) SetNillableRankPosition(v *int) *RatingHistoryUpdateOne {
	if v != nil {
		_u.SetRankPosition(*v)
	}
	return _u
}

// AddRankPosition adds value to the "rank_position" field.
func (_u *RatingHistoryUpdateOne) AddRankPosition(v int) *RatingHistoryUpdateOne {
	_u.mutation.AddRankPosition(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RatingHistoryUpdateOne) SetUser(v *User) *RatingHistoryUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetContest sets the "contest" edge to the Contest entity.
func (_u *RatingHistoryUpdateOne) SetContest(v *Contest) *RatingHistoryUpdateOne {
	return _u.SetContestID(v.ID)
}

// Mutation returns the RatingHistoryMutation object of the builder.
func (_u *RatingHistoryUpdateOne) Mutation() *RatingHistoryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RatingHistoryUpdateOne) ClearUser() *RatingHistoryUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearContest clears the "contest" edge to the Contest entity.
func (_u *RatingHistoryUpdateOne) ClearContest() *RatingHistoryUpdateOne {
	_u.mutation.ClearContest()
	return _u
}

// Where appends a list predicates to the RatingHistoryUpdate builder.
func (_u *RatingHistoryUpdateOne) Where(ps ...predicate.RatingHistory) *RatingHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RatingHistoryUpdateOne) Select(field string, fields ...string) *RatingHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RatingHistory entity.
func (_u *RatingHistoryUpdateOne) Save(ctx context.Context) (*RatingHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RatingHistoryUpdateOne) SaveX(ctx context.Context) *RatingHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RatingHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RatingHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RatingHistoryUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "RatingHistory.user"`)
	}
	if _u.mutation.ContestCleared() && len(_u.mutation.ContestIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "RatingHistory.contest"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RatingHistoryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RatingHistoryUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RatingHistoryUpdateOne) sqlSave(ctx context.Context) (_node *RatingHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ratinghistory.Table, ratinghistory.Columns, sqlgraph.NewFieldSpec(ratinghistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`generate: missing "RatingHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ratinghistory.FieldID)
		for _, f := range fields {
			if !ratinghistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("generate: invalid field %q for query", f)}
			}
			if f != ratinghistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OldRating(); ok {
		_spec.SetField(ratinghistory.FieldOldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOldRating(); ok {
		_spec.AddField(ratinghistory.FieldOldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NewRating(); ok {
		_spec.SetField(ratinghistory.FieldNewRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNewRating(); ok {
		_spec.AddField(ratinghistory.FieldNewRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RankPosition(); ok {
		_spec.SetField(ratinghistory.FieldRankPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRankPosition(); ok {
		_spec.AddField(ratinghistory.FieldRankPosition, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ratinghistory.UserTable,
			Columns: []string{ratinghistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ratinghistory.UserTable,
			Columns: []string{ratinghistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ratinghistory.ContestTable,
			Columns: []string{ratinghistory.ContestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ratinghistory.ContestTable,
			Columns: []string{ratinghistory.ContestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RatingHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ratinghistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
