// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	stdsql "database/sql"
	"fmt"
	"sync"

	"entgo.io/ent/dialect"
)

// Tx is a transactional client that is created by calling Client.Tx().
type Tx struct {
	config
	// AttributeDefinition is the client for interacting with the AttributeDefinition builders.
	AttributeDefinition *AttributeDefinitionClient
	// Contest is the client for interacting with the Contest builders.
	Contest *ContestClient
	// ContestRegistration is the client for interacting with the ContestRegistration builders.
	ContestRegistration *ContestRegistrationClient
	// ContestStanding is the client for interacting with the ContestStanding builders.
	ContestStanding *ContestStandingClient
	// Credential is the client for interacting with the Credential builders.
	Credential *CredentialClient
	// Difficulty is the client for interacting with the Difficulty builders.
	Difficulty *DifficultyClient
	// Element is the client for interacting with the Element builders.
	Element *ElementClient
	// FederatedIdentity is the client for interacting with the FederatedIdentity builders.
	FederatedIdentity *FederatedIdentityClient
	// Level is the client for interacting with the Level builders.
	Level *LevelClient
	// Material is the client for interacting with the Material builders.
	Material *MaterialClient
	// MaterialCategory is the client for interacting with the MaterialCategory builders.
	MaterialCategory *MaterialCategoryClient
	// Permission is the client for interacting with the Permission builders.
	Permission *PermissionClient
	// Problem is the client for interacting with the Problem builders.
	Problem *ProblemClient
	// Rank is the client for interacting with the Rank builders.
	Rank *RankClient
	// Rarity is the client for interacting with the Rarity builders.
	Rarity *RarityClient
	// RatingHistory is the client for interacting with the RatingHistory builders.
	RatingHistory *RatingHistoryClient
	// Resource is the client for interacting with the Resource builders.
	Resource *ResourceClient
	// Role is the client for interacting with the Role builders.
	Role *RoleClient
	// Submission is the client for interacting with the Submission builders.
	Submission *SubmissionClient
	// Tag is the client for interacting with the Tag builders.
	Tag *TagClient
	// TestCase is the client for interacting with the TestCase builders.
	TestCase *TestCaseClient
	// Trait is the client for interacting with the Trait builders.
	Trait *TraitClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserAttributeValue is the client for interacting with the UserAttributeValue builders.
	UserAttributeValue *UserAttributeValueClient
	// UserDifficultyStats is the client for interacting with the UserDifficultyStats builders.
	UserDifficultyStats *UserDifficultyStatsClient
	// UserElementExp is the client for interacting with the UserElementExp builders.
	UserElementExp *UserElementExpClient
	// UserSolvedProblem is the client for interacting with the UserSolvedProblem builders.
	UserSolvedProblem *UserSolvedProblemClient
	// UserStats is the client for interacting with the UserStats builders.
	UserStats *UserStatsClient
	// UserTagStats is the client for interacting with the UserTagStats builders.
	UserTagStats *UserTagStatsClient
	// UserTrait is the client for interacting with the UserTrait builders.
	UserTrait *UserTraitClient

	// lazily loaded.
	client     *Client
	clientOnce sync.Once
	// ctx lives for the life of the transaction. It is
	// the same context used by the underlying connection.
	ctx context.Context
}

type (
	// Committer is the interface that wraps the Commit method.
	Committer interface {
		Commit(context.Context, *Tx) error
	}

	// The CommitFunc type is an adapter to allow the use of ordinary
	// function as a Committer. If f is a function with the appropriate
	// signature, CommitFunc(f) is a Committer that calls f.
	CommitFunc func(context.Context, *Tx) error

	// CommitHook defines the "commit middleware". A function that gets a Committer
	// and returns a Committer. For example:
	//
	//	hook := func(next ent.Committer) ent.Committer {
	//		return ent.CommitFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Commit(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	CommitHook func(Committer) Committer
)

// Commit calls f(ctx, m).
func (f CommitFunc) Commit(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Commit commits the transaction.
func (tx *Tx) Commit() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Committer = CommitFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Commit()
	})
	txDriver.mu.Lock()
	hooks := append([]CommitHook(nil), txDriver.onCommit...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Commit(tx.ctx, tx)
}

// OnCommit adds a hook to call on commit.
func (tx *Tx) OnCommit(f CommitHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onCommit = append(txDriver.onCommit, f)
	txDriver.mu.Unlock()
}

type (
	// Rollbacker is the interface that wraps the Rollback method.
	Rollbacker interface {
		Rollback(context.Context, *Tx) error
	}

	// The RollbackFunc type is an adapter to allow the use of ordinary
	// function as a Rollbacker. If f is a function with the appropriate
	// signature, RollbackFunc(f) is a Rollbacker that calls f.
	RollbackFunc func(context.Context, *Tx) error

	// RollbackHook defines the "rollback middleware". A function that gets a Rollbacker
	// and returns a Rollbacker. For example:
	//
	//	hook := func(next ent.Rollbacker) ent.Rollbacker {
	//		return ent.RollbackFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Rollback(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	RollbackHook func(Rollbacker) Rollbacker
)

// Rollback calls f(ctx, m).
func (f RollbackFunc) Rollback(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Rollback rollbacks the transaction.
func (tx *Tx) Rollback() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Rollbacker = RollbackFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Rollback()
	})
	txDriver.mu.Lock()
	hooks := append([]RollbackHook(nil), txDriver.onRollback...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Rollback(tx.ctx, tx)
}

// OnRollback adds a hook to call on rollback.
func (tx *Tx) OnRollback(f RollbackHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onRollback = append(txDriver.onRollback, f)
	txDriver.mu.Unlock()
}

// Client returns a Client that binds to current transaction.
func (tx *Tx) Client() *Client {
	tx.clientOnce.Do(func() {
		tx.client = &Client{config: tx.config}
		tx.client.init()
	})
	return tx.client
}

func (tx *Tx) init() {
	tx.AttributeDefinition = NewAttributeDefinitionClient(tx.config)
	tx.Contest = NewContestClient(tx.config)
	tx.ContestRegistration = NewContestRegistrationClient(tx.config)
	tx.ContestStanding = NewContestStandingClient(tx.config)
	tx.Credential = NewCredentialClient(tx.config)
	tx.Difficulty = NewDifficultyClient(tx.config)
	tx.Element = NewElementClient(tx.config)
	tx.FederatedIdentity = NewFederatedIdentityClient(tx.config)
	tx.Level = NewLevelClient(tx.config)
	tx.Material = NewMaterialClient(tx.config)
	tx.MaterialCategory = NewMaterialCategoryClient(tx.config)
	tx.Permission = NewPermissionClient(tx.config)
	tx.Problem = NewProblemClient(tx.config)
	tx.Rank = NewRankClient(tx.config)
	tx.Rarity = NewRarityClient(tx.config)
	tx.RatingHistory = NewRatingHistoryClient(tx.config)
	tx.Resource = NewResourceClient(tx.config)
	tx.Role = NewRoleClient(tx.config)
	tx.Submission = NewSubmissionClient(tx.config)
	tx.Tag = NewTagClient(tx.config)
	tx.TestCase = NewTestCaseClient(tx.config)
	tx.Trait = NewTraitClient(tx.config)
	tx.User = NewUserClient(tx.config)
	tx.UserAttributeValue = NewUserAttributeValueClient(tx.config)
	tx.UserDifficultyStats = NewUserDifficultyStatsClient(tx.config)
	tx.UserElementExp = NewUserElementExpClient(tx.config)
	tx.UserSolvedProblem = NewUserSolvedProblemClient(tx.config)
	tx.UserStats = NewUserStatsClient(tx.config)
	tx.UserTagStats = NewUserTagStatsClient(tx.config)
	tx.UserTrait = NewUserTraitClient(tx.config)
}

// txDriver wraps the given dialect.Tx with a nop dialect.Driver implementation.
// The idea is to support transactions without adding any extra code to the builders.
// When a builder calls to driver.Tx(), it gets the same dialect.Tx instance.
// Commit and Rollback are nop for the internal builders and the user must call one
// of them in order to commit or rollback the transaction.
//
// If a closed transaction is embedded in one of the generated entities, and the entity
// applies a query, for example: AttributeDefinition.QueryXXX(), the query will be executed
// through the driver which created this transaction.
//
// Note that txDriver is not goroutine safe.
type txDriver struct {
	// the driver we started the transaction from.
	drv dialect.Driver
	// tx is the underlying transaction.
	tx dialect.Tx
	// completion hooks.
	mu         sync.Mutex
	onCommit   []CommitHook
	onRollback []RollbackHook
}

// newTx creates a new transactional driver.
func newTx(ctx context.Context, drv dialect.Driver) (*txDriver, error) {
	tx, err := drv.Tx(ctx)
	if err != nil {
		return nil, err
	}
	return &txDriver{tx: tx, drv: drv}, nil
}

// Tx returns the transaction wrapper (txDriver) to avoid Commit or Rollback calls
// from the internal builders. Should be called only by the internal builders.
func (tx *txDriver) Tx(context.Context) (dialect.Tx, error) { return tx, nil }

// Dialect returns the dialect of the driver we started the transaction from.
func (tx *txDriver) Dialect() string { return tx.drv.Dialect() }

// Close is a nop close.
func (*txDriver) Close() error { return nil }

// Commit is a nop commit for the internal builders.
// User must call `Tx.Commit` in order to commit the transaction.
func (*txDriver) Commit() error { return nil }

// Rollback is a nop rollback for the internal builders.
// User must call `Tx.Rollback` in order to rollback the transaction.
func (*txDriver) Rollback() error { return nil }

// Exec calls tx.Exec.
func (tx *txDriver) Exec(ctx context.Context, query string, args, v any) error {
	return tx.tx.Exec(ctx, query, args, v)
}

// Query calls tx.Query.
func (tx *txDriver) Query(ctx context.Context, query string, args, v any) error {
	return tx.tx.Query(ctx, query, args, v)
}

var _ dialect.Driver = (*txDriver)(nil)

// ExecContext allows calling the underlying ExecContext method of the transaction if it is supported by it.
// See, database/sql#Tx.ExecContext for more information.
func (tx *txDriver) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := tx.tx.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Tx.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the transaction if it is supported by it.
// See, database/sql#Tx.QueryContext for more information.
func (tx *txDriver) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := tx.tx.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Tx.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
