// Code generated by ent, DO NOT EDIT.

package generate

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/huynhanx03/judgify/internal/ent/generate/role"
	"github.com/huynhanx03/judgify/internal/ent/generate/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// DeletedBy holds the value of the "deleted_by" field.
	DeletedBy *int `json:"deleted_by,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID int `json:"role_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Role holds the value of the role edge.
	Role *Role `json:"role,omitempty"`
	// Credentials holds the value of the credentials edge.
	Credentials []*Credential `json:"credentials,omitempty"`
	// Attributes holds the value of the attributes edge.
	Attributes []*UserAttributeValue `json:"attributes,omitempty"`
	// FederatedIdentities holds the value of the federated_identities edge.
	FederatedIdentities []*FederatedIdentity `json:"federated_identities,omitempty"`
	// Problems holds the value of the problems edge.
	Problems []*Problem `json:"problems,omitempty"`
	// Submissions holds the value of the submissions edge.
	Submissions []*Submission `json:"submissions,omitempty"`
	// UserTraits holds the value of the user_traits edge.
	UserTraits []*UserTrait `json:"user_traits,omitempty"`
	// UserElementExps holds the value of the user_element_exps edge.
	UserElementExps []*UserElementExp `json:"user_element_exps,omitempty"`
	// UserStats holds the value of the user_stats edge.
	UserStats []*UserStats `json:"user_stats,omitempty"`
	// SolvedProblems holds the value of the solved_problems edge.
	SolvedProblems []*UserSolvedProblem `json:"solved_problems,omitempty"`
	// DifficultyStats holds the value of the difficulty_stats edge.
	DifficultyStats []*UserDifficultyStats `json:"difficulty_stats,omitempty"`
	// TagStats holds the value of the tag_stats edge.
	TagStats []*UserTagStats `json:"tag_stats,omitempty"`
	// Contests holds the value of the contests edge.
	Contests []*Contest `json:"contests,omitempty"`
	// ContestRegistrations holds the value of the contest_registrations edge.
	ContestRegistrations []*ContestRegistration `json:"contest_registrations,omitempty"`
	// ContestStandings holds the value of the contest_standings edge.
	ContestStandings []*ContestStanding `json:"contest_standings,omitempty"`
	// RatingHistories holds the value of the rating_histories edge.
	RatingHistories []*RatingHistory `json:"rating_histories,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [16]bool
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) RoleOrErr() (*Role, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// CredentialsOrErr returns the Credentials value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CredentialsOrErr() ([]*Credential, error) {
	if e.loadedTypes[1] {
		return e.Credentials, nil
	}
	return nil, &NotLoadedError{edge: "credentials"}
}

// AttributesOrErr returns the Attributes value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AttributesOrErr() ([]*UserAttributeValue, error) {
	if e.loadedTypes[2] {
		return e.Attributes, nil
	}
	return nil, &NotLoadedError{edge: "attributes"}
}

// FederatedIdentitiesOrErr returns the FederatedIdentities value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FederatedIdentitiesOrErr() ([]*FederatedIdentity, error) {
	if e.loadedTypes[3] {
		return e.FederatedIdentities, nil
	}
	return nil, &NotLoadedError{edge: "federated_identities"}
}

// ProblemsOrErr returns the Problems value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ProblemsOrErr() ([]*Problem, error) {
	if e.loadedTypes[4] {
		return e.Problems, nil
	}
	return nil, &NotLoadedError{edge: "problems"}
}

// SubmissionsOrErr returns the Submissions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SubmissionsOrErr() ([]*Submission, error) {
	if e.loadedTypes[5] {
		return e.Submissions, nil
	}
	return nil, &NotLoadedError{edge: "submissions"}
}

// UserTraitsOrErr returns the UserTraits value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UserTraitsOrErr() ([]*UserTrait, error) {
	if e.loadedTypes[6] {
		return e.UserTraits, nil
	}
	return nil, &NotLoadedError{edge: "user_traits"}
}

// UserElementExpsOrErr returns the UserElementExps value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UserElementExpsOrErr() ([]*UserElementExp, error) {
	if e.loadedTypes[7] {
		return e.UserElementExps, nil
	}
	return nil, &NotLoadedError{edge: "user_element_exps"}
}

// UserStatsOrErr returns the UserStats value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UserStatsOrErr() ([]*UserStats, error) {
	if e.loadedTypes[8] {
		return e.UserStats, nil
	}
	return nil, &NotLoadedError{edge: "user_stats"}
}

// SolvedProblemsOrErr returns the SolvedProblems value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SolvedProblemsOrErr() ([]*UserSolvedProblem, error) {
	if e.loadedTypes[9] {
		return e.SolvedProblems, nil
	}
	return nil, &NotLoadedError{edge: "solved_problems"}
}

// DifficultyStatsOrErr returns the DifficultyStats value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) DifficultyStatsOrErr() ([]*UserDifficultyStats, error) {
	if e.loadedTypes[10] {
		return e.DifficultyStats, nil
	}
	return nil, &NotLoadedError{edge: "difficulty_stats"}
}

// TagStatsOrErr returns the TagStats value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TagStatsOrErr() ([]*UserTagStats, error) {
	if e.loadedTypes[11] {
		return e.TagStats, nil
	}
	return nil, &NotLoadedError{edge: "tag_stats"}
}

// ContestsOrErr returns the Contests value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ContestsOrErr() ([]*Contest, error) {
	if e.loadedTypes[12] {
		return e.Contests, nil
	}
	return nil, &NotLoadedError{edge: "contests"}
}

// ContestRegistrationsOrErr returns the ContestRegistrations value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ContestRegistrationsOrErr() ([]*ContestRegistration, error) {
	if e.loadedTypes[13] {
		return e.ContestRegistrations, nil
	}
	return nil, &NotLoadedError{edge: "contest_registrations"}
}

// ContestStandingsOrErr returns the ContestStandings value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ContestStandingsOrErr() ([]*ContestStanding, error) {
	if e.loadedTypes[14] {
		return e.ContestStandings, nil
	}
	return nil, &NotLoadedError{edge: "contest_standings"}
}

// RatingHistoriesOrErr returns the RatingHistories value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) RatingHistoriesOrErr() ([]*RatingHistory, error) {
	if e.loadedTypes[15] {
		return e.RatingHistories, nil
	}
	return nil, &NotLoadedError{edge: "rating_histories"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldID, user.FieldDeletedBy, user.FieldRoleID:
			values[i] = new(sql.NullInt64)
		case user.FieldUsername:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt, user.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case user.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case user.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(int)
				*_m.DeletedBy = int(value.Int64)
			}
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case user.FieldRoleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRole queries the "role" edge of the User entity.
func (_m *User) QueryRole() *RoleQuery {
	return NewUserClient(_m.config).QueryRole(_m)
}

// QueryCredentials queries the "credentials" edge of the User entity.
func (_m *User) QueryCredentials() *CredentialQuery {
	return NewUserClient(_m.config).QueryCredentials(_m)
}

// QueryAttributes queries the "attributes" edge of the User entity.
func (_m *User) QueryAttributes() *UserAttributeValueQuery {
	return NewUserClient(_m.config).QueryAttributes(_m)
}

// QueryFederatedIdentities queries the "federated_identities" edge of the User entity.
func (_m *User) QueryFederatedIdentities() *FederatedIdentityQuery {
	return NewUserClient(_m.config).QueryFederatedIdentities(_m)
}

// QueryProblems queries the "problems" edge of the User entity.
func (_m *User) QueryProblems() *ProblemQuery {
	return NewUserClient(_m.config).QueryProblems(_m)
}

// QuerySubmissions queries the "submissions" edge of the User entity.
func (_m *User) QuerySubmissions() *SubmissionQuery {
	return NewUserClient(_m.config).QuerySubmissions(_m)
}

// QueryUserTraits queries the "user_traits" edge of the User entity.
func (_m *User) QueryUserTraits() *UserTraitQuery {
	return NewUserClient(_m.config).QueryUserTraits(_m)
}

// QueryUserElementExps queries the "user_element_exps" edge of the User entity.
func (_m *User) QueryUserElementExps() *UserElementExpQuery {
	return NewUserClient(_m.config).QueryUserElementExps(_m)
}

// QueryUserStats queries the "user_stats" edge of the User entity.
func (_m *User) QueryUserStats() *UserStatsQuery {
	return NewUserClient(_m.config).QueryUserStats(_m)
}

// QuerySolvedProblems queries the "solved_problems" edge of the User entity.
func (_m *User) QuerySolvedProblems() *UserSolvedProblemQuery {
	return NewUserClient(_m.config).QuerySolvedProblems(_m)
}

// QueryDifficultyStats queries the "difficulty_stats" edge of the User entity.
func (_m *User) QueryDifficultyStats() *UserDifficultyStatsQuery {
	return NewUserClient(_m.config).QueryDifficultyStats(_m)
}

// QueryTagStats queries the "tag_stats" edge of the User entity.
func (_m *User) QueryTagStats() *UserTagStatsQuery {
	return NewUserClient(_m.config).QueryTagStats(_m)
}

// QueryContests queries the "contests" edge of the User entity.
func (_m *User) QueryContests() *ContestQuery {
	return NewUserClient(_m.config).QueryContests(_m)
}

// QueryContestRegistrations queries the "contest_registrations" edge of the User entity.
func (_m *User) QueryContestRegistrations() *ContestRegistrationQuery {
	return NewUserClient(_m.config).QueryContestRegistrations(_m)
}

// QueryContestStandings queries the "contest_standings" edge of the User entity.
func (_m *User) QueryContestStandings() *ContestStandingQuery {
	return NewUserClient(_m.config).QueryContestStandings(_m)
}

// QueryRatingHistories queries the "rating_histories" edge of the User entity.
func (_m *User) QueryRatingHistories() *RatingHistoryQuery {
	return NewUserClient(_m.config).QueryRatingHistories(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("generate: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteByte(')')
	return builder.String()
}

func (_m *User) GetID() int {
	return _m.ID
}

func (_m *User) SetID(id int) {
	_m.ID = id
}

// Users is a parsable slice of User.
type Users []*User
