// Code generated by ent, DO NOT EDIT.

package generate

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/huynhanx03/judgify/internal/ent/generate/tag"
	"github.com/huynhanx03/judgify/internal/ent/generate/user"
	"github.com/huynhanx03/judgify/internal/ent/generate/usertagstats"
)

// UserTagStats is the model entity for the UserTagStats schema.
type UserTagStats struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// TagID holds the value of the "tag_id" field.
	TagID int `json:"tag_id,omitempty"`
	// SolvedCount holds the value of the "solved_count" field.
	SolvedCount int `json:"solved_count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserTagStatsQuery when eager-loading is set.
	Edges        UserTagStatsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserTagStatsEdges holds the relations/edges for other nodes in the graph.
type UserTagStatsEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Tag holds the value of the tag edge.
	Tag *Tag `json:"tag,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserTagStatsEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// TagOrErr returns the Tag value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserTagStatsEdges) TagOrErr() (*Tag, error) {
	if e.Tag != nil {
		return e.Tag, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: tag.Label}
	}
	return nil, &NotLoadedError{edge: "tag"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserTagStats) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usertagstats.FieldID, usertagstats.FieldUserID, usertagstats.FieldTagID, usertagstats.FieldSolvedCount:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserTagStats fields.
func (_m *UserTagStats) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usertagstats.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case usertagstats.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case usertagstats.FieldTagID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tag_id", values[i])
			} else if value.Valid {
				_m.TagID = int(value.Int64)
			}
		case usertagstats.FieldSolvedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field solved_count", values[i])
			} else if value.Valid {
				_m.SolvedCount = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserTagStats.
// This includes values selected through modifiers, order, etc.
func (_m *UserTagStats) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserTagStats entity.
func (_m *UserTagStats) QueryUser() *UserQuery {
	return NewUserTagStatsClient(_m.config).QueryUser(_m)
}

// QueryTag queries the "tag" edge of the UserTagStats entity.
func (_m *UserTagStats) QueryTag() *TagQuery {
	return NewUserTagStatsClient(_m.config).QueryTag(_m)
}

// Update returns a builder for updating this UserTagStats.
// Note that you need to call UserTagStats.Unwrap() before calling this method if this UserTagStats
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserTagStats) Update() *UserTagStatsUpdateOne {
	return NewUserTagStatsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserTagStats entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserTagStats) Unwrap() *UserTagStats {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("generate: UserTagStats is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserTagStats) String() string {
	var builder strings.Builder
	builder.WriteString("UserTagStats(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("tag_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TagID))
	builder.WriteString(", ")
	builder.WriteString("solved_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SolvedCount))
	builder.WriteByte(')')
	return builder.String()
}

func (_m *UserTagStats) GetID() int {
	return _m.ID
}

func (_m *UserTagStats) SetID(id int) {
	_m.ID = id
}

// UserTagStatsSlice is a parsable slice of UserTagStats.
type UserTagStatsSlice []*UserTagStats
