// Code generated by ent, DO NOT EDIT.

package generate

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/huynhanx03/judgify/internal/ent/generate/problem"
	"github.com/huynhanx03/judgify/internal/ent/generate/user"
	"github.com/huynhanx03/judgify/internal/ent/generate/usersolvedproblem"
)

// UserSolvedProblem is the model entity for the UserSolvedProblem schema.
type UserSolvedProblem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// ProblemID holds the value of the "problem_id" field.
	ProblemID int `json:"problem_id,omitempty"`
	// SolvedAt holds the value of the "solved_at" field.
	SolvedAt time.Time `json:"solved_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserSolvedProblemQuery when eager-loading is set.
	Edges        UserSolvedProblemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserSolvedProblemEdges holds the relations/edges for other nodes in the graph.
type UserSolvedProblemEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Problem holds the value of the problem edge.
	Problem *Problem `json:"problem,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserSolvedProblemEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ProblemOrErr returns the Problem value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserSolvedProblemEdges) ProblemOrErr() (*Problem, error) {
	if e.Problem != nil {
		return e.Problem, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: problem.Label}
	}
	return nil, &NotLoadedError{edge: "problem"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserSolvedProblem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usersolvedproblem.FieldID, usersolvedproblem.FieldUserID, usersolvedproblem.FieldProblemID:
			values[i] = new(sql.NullInt64)
		case usersolvedproblem.FieldSolvedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserSolvedProblem fields.
func (_m *UserSolvedProblem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usersolvedproblem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case usersolvedproblem.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case usersolvedproblem.FieldProblemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field problem_id", values[i])
			} else if value.Valid {
				_m.ProblemID = int(value.Int64)
			}
		case usersolvedproblem.FieldSolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field solved_at", values[i])
			} else if value.Valid {
				_m.SolvedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserSolvedProblem.
// This includes values selected through modifiers, order, etc.
func (_m *UserSolvedProblem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserSolvedProblem entity.
func (_m *UserSolvedProblem) QueryUser() *UserQuery {
	return NewUserSolvedProblemClient(_m.config).QueryUser(_m)
}

// QueryProblem queries the "problem" edge of the UserSolvedProblem entity.
func (_m *UserSolvedProblem) QueryProblem() *ProblemQuery {
	return NewUserSolvedProblemClient(_m.config).QueryProblem(_m)
}

// Update returns a builder for updating this UserSolvedProblem.
// Note that you need to call UserSolvedProblem.Unwrap() before calling this method if this UserSolvedProblem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserSolvedProblem) Update() *UserSolvedProblemUpdateOne {
	return NewUserSolvedProblemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserSolvedProblem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserSolvedProblem) Unwrap() *UserSolvedProblem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("generate: UserSolvedProblem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserSolvedProblem) String() string {
	var builder strings.Builder
	builder.WriteString("UserSolvedProblem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("problem_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProblemID))
	builder.WriteString(", ")
	builder.WriteString("solved_at=")
	builder.WriteString(_m.SolvedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

func (_m *UserSolvedProblem) GetID() int {
	return _m.ID
}

func (_m *UserSolvedProblem) SetID(id int) {
	_m.ID = id
}

// UserSolvedProblems is a parsable slice of UserSolvedProblem.
type UserSolvedProblems []*UserSolvedProblem
