/**
 * Vietnamese text constants for the UI.
 * All user-facing strings are defined here to support future i18n.
 * When adding multi-language support, replace this with a proper i18n library.
 */

export const TEXT = {
  // App-level
  APP_NAME: "Judgify",
  APP_DESCRIPTION: "Thánh Địa Luyện Code",
  APP_FULL_TITLE: "Judgify - Thánh Địa Luyện Code",

  // Navigation
  NAV: {
    ARENA: "Luyện Tập",
    MATERIALS: "Tàng Kinh Các",
    CONTEST: "Đại Hội Tỷ Thí",
    RANKING: "Bảng Phong Thần",
    PROFILE: "Hồ Sơ Tu Luyện",
    SETTINGS: "Cài Đặt",
    LOGOUT: "Đăng Xuất",
  },

  // Header User Dropdown
  HEADER: {
    AVATAR_FALLBACK: "ĐH",
    GUEST_NAME: "Đạo Hữu Vô Danh",
    GUEST_RANK: "Trúc Cơ Kỳ",
  },

  // Auth
  AUTH: {
    LOGIN: "Đăng Nhập",
    REGISTER: "Đăng Ký",
    USERNAME: "Pháp Danh",
    USERNAME_PLACEHOLDER: "Nhập pháp danh của bạn",
    PASSWORD: "Mật Khẩu",
    PASSWORD_PLACEHOLDER: "Nhập mật khẩu",
    FORGOT_PASSWORD: "Quên Mật Khẩu?",
    NO_ACCOUNT: "Chưa có tài khoản?",
    HAS_ACCOUNT: "Đã có tài khoản?",
    FIRST_NAME: "Họ",
    LAST_NAME: "Tên",
    BIRTHDAY: "Ngày Sinh",
    GENDER: "Giới Tính",
    GENDER_MALE: "Nam",
    GENDER_FEMALE: "Nữ",
    GENDER_OTHER: "Khác",
    WELCOME_BACK: "Chào Mừng Trở Lại",
    WELCOME_SUBTITLE: "Hãy đăng nhập để tiếp tục hành trình tu luyện",
    REGISTER_TITLE: "Gia Nhập Tu Viện",
    REGISTER_SUBTITLE: "Tạo tài khoản để bắt đầu hành trình tu luyện",
    CONFIRM_PASSWORD: "Xác Nhận Mật Khẩu",
    CONFIRM_PASSWORD_PLACEHOLDER: "Nhập lại mật khẩu",
    FIRST_NAME_PLACEHOLDER: "Nhập họ",
    LAST_NAME_PLACEHOLDER: "Nhập tên",
    PASSWORD_MISMATCH: "Mật khẩu xác nhận không khớp",
    REGISTER_SUCCESS: "Đăng ký thành công! Đang chuyển hướng...",
    FORGOT_PASSWORD_TITLE: "Quên Mật Khẩu",
    FORGOT_PASSWORD_SUBTITLE: "Nhập pháp danh để khôi phục mật khẩu",
    FORGOT_PASSWORD_SUCCESS: "Đã gửi liên kết khôi phục mật khẩu. Kiểm tra email của bạn.",
    BACK_TO_LOGIN: "Quay lại đăng nhập",
    SEND_RESET_LINK: "Gửi Liên Kết Khôi Phục",
    RESET_PASSWORD_TITLE: "Đặt Lại Mật Khẩu",
    RESET_PASSWORD_SUBTITLE: "Nhập mật khẩu mới cho tài khoản của bạn",
    NEW_PASSWORD: "Mật Khẩu Mới",
    NEW_PASSWORD_PLACEHOLDER: "Nhập mật khẩu mới",
    RESET_PASSWORD: "Đặt Lại Mật Khẩu",
    RESET_PASSWORD_SUCCESS: "Đặt lại mật khẩu thành công!",
  },

  // Profile
  PROFILE: {
    TITLE: "Hồ Sơ Tu Luyện",
    SUBTITLE: "Thông tin cá nhân và tiến trình tu luyện",
    EDIT_PROFILE: "Chỉnh Sửa Hồ Sơ",
    SAVE_CHANGES: "Lưu Thay Đổi",
    CANCEL_EDIT: "Hủy",
    UPDATE_SUCCESS: "Cập nhật hồ sơ thành công!",
    JOINED_DATE: "Ngày Gia Nhập",
    RANK: "Cấp Bậc",
    PROBLEMS_SOLVED: "Bài Đã Giải",
    CONTESTS_JOINED: "Đại Hội Tham Gia",
    PERSONAL_INFO: "Thông Tin Cá Nhân",
    STATISTICS: "Thống Kê Tu Luyện",
    EASY_SOLVED: "Dễ",
    MEDIUM_SOLVED: "Trung",
    HARD_SOLVED: "Khó",
    TOTAL_SUBMISSIONS: "Tổng Nộp Bài",
    ACCEPTANCE_RATE: "Tỉ Lệ AC",
  },

  // Arena
  ARENA: {
    TITLE: "Thánh Địa Luyện Tập",
    SUBTITLE: "Nơi ngưng tụ linh khí, rèn luyện pháp thuật và đột phá đạo cơ.",
    ALL: "Tất Cả",
    EASY: "Dễ",
    MEDIUM: "Trung",
    HARD: "Khó",
    PROBLEM_TITLE: "Tên Bài",
    DIFFICULTY: "Phẩm Chất",
    TAGS: "Công Pháp",
    ACCEPTANCE: "Tỉ Lệ AC",
    STATUS: "Trạng Thái",
    SOLVED: "Đã Giải",
    UNSOLVED: "Chưa Giải",
    ATTEMPTED: "Đang Thử",
    NO_PROBLEMS: "Chưa có bài tập nào",
    NO_PROBLEMS_DESC: "Đạo hữu có thể thử tìm kiếm hoặc điều chỉnh lại bộ lọc Phẩm Chất.",
    SEARCH_PLACEHOLDER: "Tìm kiếm danh tự bài tập...",
    // Filter Panel
    FILTER_BUTTON: "Lọc & Sắp Xếp",
    FILTER_TITLE: "Bộ Lọc & Sắp Xếp",
    SORT_TITLE: "Sắp Xếp Tiên Bảng",
    SORT_ACCEPTANCE: "Tỷ Lệ AC",
    SORT_SOLVED: "Đã Giải",
    DIFFICULTY_TITLE: "Phẩm Chất",
    TAGS_TITLE: "Công Pháp",
    CLEAR_FILTER: "Làm mới bộ lọc",
    ACTIVE_FILTERS: "Đang lọc:",
    CLEAR_ALL: "Xóa tất cả",
    ASC: "Tăng dần",
    DESC: "Giảm dần",
    DEFAULT: "Mặc định",
  },

  // Problem Detail
  PROBLEM: {
    BACK_TO_ARENA: "Luyện Tập",
    DESCRIPTION: "Đề Bài",
    EXAMPLES: "Ví Dụ",
    EXAMPLE: "Ví dụ",
    INPUT: "Input",
    OUTPUT: "Output",
    EXPLANATION: "Giải thích",
    COPIED: "Đã copy!",
    COPY: "Copy",
    SUBMISSION_HISTORY: "Lịch Sử Nộp Bài",
    NO_SUBMISSIONS: "Chưa có lần nộp bài nào",
    SUBMIT: "Nộp Bài",
    SUBMITTING: "Đang chấm...",
    SELECT_LANGUAGE: "Ngôn ngữ",
    SELECT_FILE: "Chọn file code",
    FILE_SELECTED: "Đã chọn",
    NO_FILE: "Chưa chọn file",
    NOT_FOUND: "Không tìm thấy bài tập",
    SUBMIT_SUCCESS: "Accepted! Chúc mừng đạo hữu đã giải thành công!",
    TIME_LIMIT: "Thời gian",
    MEMORY_LIMIT: "Bộ nhớ",
    INPUT_FORMAT: "Định dạng đầu vào",
    OUTPUT_FORMAT: "Định dạng đầu ra",
  },

  // Ranking
  RANKING: {
    TAB_RATING: "Thiên Đạo Bảng",
    TAB_LEVEL: "Tu Luyện Bảng",
    TAB_SPIRITUAL_ROOT: "Linh Căn Bảng",
    RATING_SUBTITLE: "Xếp hạng theo cảnh giới tu luyện — cấp bậc đại đạo",
    LEVEL_SUBTITLE: "Xếp hạng theo cấp độ và kinh nghiệm tu luyện",
    SPIRITUAL_ROOT_SUBTITLE: "Xếp hạng theo từng hệ linh căn",
    LEVEL: "Cấp Độ",
    EXP: "Kinh Nghiệm",
    PURITY: "Độ Thuần Khiết",
    SPIRITUAL_ROOT: "Linh Căn",
    REALM: "Cảnh Giới",
    SECT: "Tông Môn",
    POINTS: "Linh Lực",
    HERO_BADGE: "VẠN CỔ TIÊN BẢNG",
    HERO_DESC: "Nơi vinh danh những bậc đại năng có căn cốt phi phàm, khắc tên vào sử sách của giới tu chân.",
    TABLE_TITLE: "Quần Anh Hội Tụ",
    RANK_LABEL: "Thứ Hạng",
    CULTIVATOR_LABEL: "Vị Đại Năng",
  },

  // Theme
  THEME: {
    LIGHT: "Sáng",
    DARK: "Tối",
    SYSTEM: "Hệ Thống",
    TOGGLE: "Chuyển đổi giao diện",
  },

  // Common
  COMMON: {
    LOADING: "Đang tải...",
    ERROR: "Có lỗi xảy ra",
    RETRY: "Thử lại",
    SAVE: "Lưu",
    CANCEL: "Hủy",
    DELETE: "Xóa",
    EDIT: "Sửa",
    CREATE: "Tạo Mới",
    SEARCH: "Tìm Kiếm",
    FILTER: "Lọc",
    NO_DATA: "Không có dữ liệu",
    PAGE: "Trang",
    OF: "trong số",
    PREVIOUS: "Trước",
    NEXT: "Tiếp",
  },
} as const;
