/**
 * Vietnamese text constants for the UI.
 * All user-facing strings are defined here to support future i18n.
 * When adding multi-language support, replace this with a proper i18n library.
 */

export const TEXT = {
  // App-level
  APP_NAME: "Judgify",
  APP_DESCRIPTION: "Thánh Địa Luyện Code",
  APP_FULL_TITLE: "Judgify - Thánh Địa Luyện Code",

  // Navigation
  NAV: {
    ARENA: "Luyện Tập",
    MATERIALS: "Tàng Kinh Các",
    CONTEST: "Đại Hội Tỷ Thí",
    RANKING: "Bảng Phong Thần",
    PROFILE: "Hồ Sơ Tu Luyện",
    SETTINGS: "Cài Đặt",
    LOGOUT: "Đăng Xuất",
    ABOUT: "Tông Môn Bí Lục",
  },

  // Header User Dropdown
  HEADER: {
    AVATAR_FALLBACK: "ĐH",
    GUEST_NAME: "Đạo Hữu Vô Danh",
    GUEST_RANK: "Trúc Cơ Kỳ",
  },

  // Auth
  AUTH: {
    // Tabs
    TAB_LOGIN: "Đăng Nhập",
    TAB_REGISTER: "Đăng Ký",
    LOGIN: "Đăng Nhập",
    REGISTER: "Đăng Ký",
    // Login
    LOGIN_TITLE: "Đạo Hữu Quay Lại!",
    LOGIN_SUBTITLE: "Nhập danh tính để tiếp tục con đường tu tiên.",
    LOGIN_BUTTON: "ĐĂNG NHẬP",
    LOGIN_GOOGLE: "Đăng nhập bằng Google",
    // Fields
    USERNAME: "Pháp Danh",
    USERNAME_PLACEHOLDER: "Nhập pháp danh của bạn",
    PASSWORD: "Mật Khẩu",
    PASSWORD_PLACEHOLDER: "Nhập mật khẩu",
    FORGOT_PASSWORD: "Quên Mật Khẩu?",
    NO_ACCOUNT: "Chưa có tài khoản?",
    HAS_ACCOUNT: "Đã có tài khoản?",
    FIRST_NAME: "Tên",
    LAST_NAME: "Họ",
    FIRST_NAME_PLACEHOLDER: "Văn A",
    LAST_NAME_PLACEHOLDER: "Nguyễn",
    BIRTHDAY: "Ngày Sinh",
    GENDER: "Giới Tính",
    GENDER_MALE: "Nam",
    GENDER_FEMALE: "Nữ",
    GENDER_OTHER: "Khác",
    // Register
    REGISTER_TITLE: "Gia Nhập Tu Viện",
    REGISTER_SUBTITLE: "Điền thông tin để bắt đầu hành trình tu luyện.",
    REGISTER_NEXT: "Tiếp Tục Tu Luyện",
    REGISTER_SUBMIT: "Xuất Sơn",
    REGISTER_BACK: "Quay Lại",
    REGISTER_MISSING_INFO: "Thiếu thông tin tiên nhân!",
    REGISTER_SUCCESS: "Đăng ký thành công!",
    // Trait Selection
    TRAIT_TITLE: "Khai Mở Thiên Mệnh",
    TRAIT_SUBTITLE: "Tung xúc xắc để nhận Căn Cốt và Thiên Phú ngẫu nhiên.",
    TRAIT_ROLL_BUTTON: "Tung Vận Mệnh",
    TRAIT_REROLL: "Tung Lại",
    TRAIT_ROLLING: "Đang quay...",
    TRAIT_ROOT_BONE: "Căn Cốt",
    TRAIT_TALENT: "Thiên Phú",
    TRAIT_SELECT_ROOT_BONE: "Chọn 1 Căn Cốt",
    TRAIT_SELECT_TALENTS: "Chọn 3 Thiên Phú",
    TRAIT_SELECTED: "Đã chọn",
    TRAIT_ROOT_BONE_REQUIRED: "Ngài phải chọn 1 Căn Cốt!",
    TRAIT_TALENTS_REQUIRED: "Vui lòng chọn đủ 3 Thiên Phú để xuất sơn.",
    TRAIT_MAX_TALENTS: "Chỉ được mang theo tối đa 3 Thiên Phú!",
    TRAIT_FETCH_ERROR: "Không thể tải danh sách thiên mệnh.",
    // Progress steps
    STEP_INFO: "Phàm Trần",
    STEP_TRAITS: "Thiên Mệnh",
    // Other
    CONFIRM_PASSWORD: "Xác Nhận Mật Khẩu",
    CONFIRM_PASSWORD_PLACEHOLDER: "Nhập lại mật khẩu",
    PASSWORD_MISMATCH: "Mật khẩu xác nhận không khớp",
    WELCOME_BACK: "Chào Mừng Trở Lại",
    WELCOME_SUBTITLE: "Hãy đăng nhập để tiếp tục hành trình tu luyện",
    FORGOT_PASSWORD_TITLE: "Quên Mật Khẩu",
    FORGOT_PASSWORD_SUBTITLE: "Nhập pháp danh để khôi phục mật khẩu",
    FORGOT_PASSWORD_SUCCESS: "Đã gửi liên kết khôi phục mật khẩu. Kiểm tra email của bạn.",
    BACK_TO_LOGIN: "Quay lại đăng nhập",
    SEND_RESET_LINK: "Gửi Liên Kết Khôi Phục",
    RESET_PASSWORD_TITLE: "Đặt Lại Mật Khẩu",
    RESET_PASSWORD_SUBTITLE: "Nhập mật khẩu mới cho tài khoản của bạn",
    NEW_PASSWORD: "Mật Khẩu Mới",
    NEW_PASSWORD_PLACEHOLDER: "Nhập mật khẩu mới",
    RESET_PASSWORD: "Đặt Lại Mật Khẩu",
    RESET_PASSWORD_SUCCESS: "Đặt lại mật khẩu thành công!",
  },

  // Profile
  PROFILE: {
    TITLE: "Hồ Sơ Tu Luyện",
    SUBTITLE: "Thông tin cá nhân và tiến trình tu luyện",
    EDIT_PROFILE: "Chỉnh Sửa Hồ Sơ",
    SAVE_CHANGES: "Lưu Thay Đổi",
    CANCEL_EDIT: "Hủy",
    UPDATE_SUCCESS: "Cập nhật hồ sơ thành công!",
    JOINED_DATE: "Ngày Gia Nhập",
    BIRTHDAY: "Đản Thần",
    RANK: "Cấp Bậc",
    CULTIVATION_PROGRESS: "Tu Luyện Tiến Trình",
    CULTIVATION_SUBTITLE: "Cảnh giới, cấp bậc và linh căn ngũ hành",
    CULTIVATION_REALM: "Cảnh Giới",
    CULTIVATION_RANK: "Cấp Bậc",
    CULTIVATION_EXP_TO_BREAK: "EXP để đột phá",
    CULTIVATION_RATING_TO_NEXT: "Rating để thăng cảnh",
    CULTIVATION_NO_ELEMENTS: "Chưa có dữ liệu ngũ hành",
    CULTIVATION_MAX_LEVEL: "Đỉnh Phong",
    CULTIVATION_MAX_RANK: "Vô Song",
    CULTIVATION_NEXT: "→",
    TRAITS_TITLE: "Căn Cốt & Thiên Phú",
    TRAITS_SUBTITLE: "Thể chất bẩm sinh và tài năng thiên bẩm",
    TALENTS_LABEL: "Thiên Phú",
    NO_ROOT_BONE: "Chưa có căn cốt",
    NO_TALENTS: "Chưa có thiên phú",
    EDIT_TOOLTIP: "Chỉnh sửa hồ sơ",
    LOGOUT_TOOLTIP: "Đăng xuất",
    PROBLEMS_SOLVED: "Bài Đã Giải",
    CONTESTS_JOINED: "Đại Hội Tham Gia",
    PERSONAL_INFO: "Thông Tin Cá Nhân",
    STATISTICS: "Thống Kê Tu Luyện",
    EASY_SOLVED: "Dễ",
    MEDIUM_SOLVED: "Trung",
    HARD_SOLVED: "Khó",
    TOTAL_SUBMISSIONS: "Tổng Nộp Bài",
    ACCEPTANCE_RATE: "Tỉ Lệ AC",
  },

  STATS: {
    TITLE: "Thống Kê Tu Luyện",
    SUBTITLE: "Tổng quan bài đã giải, tỉ lệ AC và phân bổ theo độ khó",
    TOTAL_SOLVED: "Bài Đã Giải",
    TOTAL_SUBMISSIONS: "Tổng Nộp Bài",
    AC_RATE: "Tỉ Lệ AC",
    BY_DIFFICULTY: "Theo Độ Khó",
    BY_TAG: "Theo Chủ Đề",
    NO_STATS: "Chưa có thống kê — hãy nộp bài đầu tiên!",
    BAI: "bài",
    TAGS_TITLE: "Chủ Đề Đã Chinh Phục",
    TAGS_SUBTITLE: "Các chủ đề đã giải được, phân loại theo ngũ hành linh căn",
    NO_TAGS: "Chưa chinh phục chủ đề nào",
  },

  // Arena
  ARENA: {
    TITLE: "Thánh Địa Luyện Tập",
    SUBTITLE: "Nơi ngưng tụ linh khí, rèn luyện pháp thuật và đột phá đạo cơ.",
    ALL: "Tất Cả",
    EASY: "Dễ",
    MEDIUM: "Trung",
    HARD: "Khó",
    PROBLEM_TITLE: "Tên Bài",
    DIFFICULTY: "Phẩm Chất",
    TAGS: "Công Pháp",
    ACCEPTANCE: "Tỉ Lệ AC",
    STATUS: "Trạng Thái",
    SOLVED: "Đã Giải",
    UNSOLVED: "Chưa Giải",
    ATTEMPTED: "Đang Thử",
    NO_PROBLEMS: "Chưa có bài tập nào",
    NO_PROBLEMS_DESC: "Đạo hữu có thể thử tìm kiếm hoặc điều chỉnh lại bộ lọc Phẩm Chất.",
    SEARCH_PLACEHOLDER: "Tìm kiếm danh tự bài tập...",
    // Filter Panel
    FILTER_BUTTON: "Lọc & Sắp Xếp",
    FILTER_TITLE: "Bộ Lọc & Sắp Xếp",
    SORT_TITLE: "Sắp Xếp Tiên Bảng",
    SORT_ACCEPTANCE: "Tỷ Lệ AC",
    SORT_SOLVED: "Đã Giải",
    DIFFICULTY_TITLE: "Phẩm Chất",
    TAGS_TITLE: "Công Pháp",
    CLEAR_FILTER: "Làm mới bộ lọc",
    ACTIVE_FILTERS: "Đang lọc:",
    CLEAR_ALL: "Xóa tất cả",
    ASC: "Tăng dần",
    DESC: "Giảm dần",
    DEFAULT: "Mặc định",
  },

  // Contest
  CONTEST: {
    TITLE: "Đại Hội Tỷ Thí",
    SUBTITLE: "Các giải đấu lập trình định kỳ — thi đấu, leo rank, tranh danh hiệu.",
    SEARCH_PLACEHOLDER: "Tìm kiếm cuộc thi...",
    NO_CONTESTS: "Chưa có cuộc thi nào",
    NO_CONTESTS_DESC: "Hiện chưa có đại hội nào được tổ chức.",
    REGISTER: "Đăng Ký Tham Gia",
    UNREGISTER: "Hủy Đăng Ký",
    REGISTERED: "Đã Đăng Ký",
    REGISTER_SUCCESS: "Đăng ký thành công!",
    UNREGISTER_SUCCESS: "Đã hủy đăng ký.",
    PARTICIPANTS: "Người Tham Gia",
    START_TIME: "Bắt Đầu",
    END_TIME: "Kết Thúc",
    STATUS: "Trạng Thái",
    STANDINGS: "Bảng Xếp Hạng",
    RANK: "Hạng",
    USER: "Đại Năng",
    SOLVED: "AC",
    PENALTY: "Phạt",
    PROBLEMS: "Bài",
    MAX_PARTICIPANTS: "Giới Hạn",
    // Status labels
    STATUS_DRAFT: "Nháp",
    STATUS_UPCOMING: "Sắp Diễn Ra",
    STATUS_RUNNING: "Đang Diễn Ra",
    STATUS_ENDED: "Đã Kết Thúc",
    // Detail
    BACK_TO_LIST: "Đại Hội Tỷ Thí",
    DETAIL_DESCRIPTION: "Mô Tả",
    DETAIL_INFO: "Thông Tin",
    DETAIT_STANDINGS: "Bảng Xếp Hạng",
    // Rating changes
    RATING_CHANGES: "Biến Động Rating",
    RATING_OLD: "Rating Cũ",
    RATING_NEW: "Rating Mới",
    RATING_DELTA: "Thay Đổi",
    NO_RATING_CHANGES: "Chưa có dữ liệu rating",
    NO_RATING_CHANGES_DESC: "Rating sẽ được tính sau khi cuộc thi kết thúc.",
  },

  // Problem Detail
  PROBLEM: {
    BACK_TO_ARENA: "Luyện Tập",
    DESCRIPTION: "Đề Bài",
    EXAMPLES: "Ví Dụ",
    EXAMPLE: "Ví dụ",
    INPUT: "Input",
    OUTPUT: "Output",
    EXPLANATION: "Giải thích",
    COPIED: "Đã copy!",
    COPY: "Copy",
    SUBMISSION_HISTORY: "Lịch Sử Nộp Bài",
    NO_SUBMISSIONS: "Chưa có lần nộp bài nào",
    SUBMIT: "Nộp Bài",
    SUBMITTING: "Đang chấm...",
    SELECT_LANGUAGE: "Ngôn ngữ",
    SELECT_FILE: "Chọn file code",
    FILE_SELECTED: "Đã chọn",
    NO_FILE: "Chưa chọn file",
    NOT_FOUND: "Không tìm thấy bài tập",
    SUBMIT_SUCCESS: "Accepted! Chúc mừng đạo hữu đã giải thành công!",
    TIME_LIMIT: "Thời gian",
    MEMORY_LIMIT: "Bộ nhớ",
    INPUT_FORMAT: "Định dạng đầu vào",
    OUTPUT_FORMAT: "Định dạng đầu ra",
    // Submission history table
    LOADING_SUBMISSIONS: "Đang tải lịch sử nộp bài...",
    COL_RESULT: "Kết Quả",
    COL_LANGUAGE: "Ngôn Ngữ",
    COL_TESTS: "Test",
    COL_TIME: "Thời Gian",
    COL_MEMORY: "Bộ Nhớ",
    COL_SUBMITTED_AT: "Nộp Lúc",
    // Submission detail sheet
    DETAIL_TITLE: "Chi Tiết Nộp Bài",
    DETAIL_SOURCE_CODE: "Source Code",
    DETAIL_ERROR: "Thông Báo Lỗi",
    DETAIL_STATS_TESTS: "Test qua",
    DETAIL_STATS_TIME: "Thời gian",
    DETAIL_STATS_MEMORY: "Bộ nhớ",
    DETAIL_COPY: "Copy",
    DETAIL_COPIED: "Đã copy!",
  },

  // Ranking
  RANKING: {
    TAB_RATING: "Thiên Đạo Bảng",
    TAB_LEVEL: "Tu Luyện Bảng",
    TAB_SPIRITUAL_ROOT: "Linh Căn Bảng",
    RATING_SUBTITLE: "Xếp hạng theo cảnh giới tu luyện — cấp bậc đại đạo",
    LEVEL_SUBTITLE: "Xếp hạng theo cấp độ và kinh nghiệm tu luyện",
    SPIRITUAL_ROOT_SUBTITLE: "Xếp hạng theo từng hệ linh căn",
    LEVEL: "Cấp Độ",
    EXP: "Kinh Nghiệm",
    PURITY: "Độ Thuần Khiết",
    SPIRITUAL_ROOT: "Linh Căn",
    REALM: "Cảnh Giới",
    SECT: "Tông Môn",
    POINTS: "Linh Lực",
    HERO_BADGE: "VẠN CỔ TIÊN BẢNG",
    HERO_DESC: "Nơi vinh danh những bậc đại năng có căn cốt phi phàm, khắc tên vào sử sách của giới tu chân.",
    TABLE_TITLE: "Quần Anh Hội Tụ",
    RANK_LABEL: "Thứ Hạng",
    CULTIVATOR_LABEL: "Vị Đại Năng",
  },

  // Theme
  THEME: {
    LIGHT: "Sáng",
    DARK: "Tối",
    SYSTEM: "Hệ Thống",
    TOGGLE: "Chuyển đổi giao diện",
  },

  // Admin
  ADMIN: {
    // Dashboard
    DASHBOARD_TITLE: "Dashboard",
    DASHBOARD_SUBTITLE: "Tổng quan hệ thống Judgify",
    RECENT_ACTIVITY: "Hoạt Động Gần Đây",
    STAT_USERS: "Người Dùng",
    STAT_PROBLEMS: "Bài Tập",
    STAT_TAGS: "Tags",
    STAT_ROLES: "Vai Trò",

    // Users page
    USERS_TITLE: "Người Dùng",
    USERS_SUBTITLE: "Quản lý tài khoản người dùng trong hệ thống",
    USERS_CREATE: "Tạo Người Dùng",
    USERS_EMPTY: "Chưa có người dùng nào",
    USERS_COL_ID: "ID",
    USERS_COL_USERNAME: "Username",
    USERS_COL_ROLE: "Vai Trò",
    USERS_COL_CREATED: "Ngày Tạo",
    USERS_DELETE_TITLE: "Xoá người dùng",
    USERS_DELETE_DESC: (username: string) => `Bạn có chắc muốn xoá "${username}"? Hành động này không thể hoàn tác.`,
    USERS_DELETE_SUCCESS: "Đã xoá người dùng",
    USERS_DELETE_ERROR: "Xoá thất bại",
    USERS_EDIT_ROLE_TITLE: "Đổi Vai Trò",
    USERS_EDIT_ROLE_DESC: (username: string) => `Cập nhật vai trò cho ${username}`,
    USERS_EDIT_ROLE_SUCCESS: "Đã cập nhật vai trò",
    USERS_EDIT_ROLE_ERROR: "Cập nhật thất bại",
    USERS_CREATE_TITLE: "Tạo Người Dùng Mới",
    USERS_CREATE_DESC: "Tạo tài khoản mới trong hệ thống",
    USERS_CREATE_SUCCESS: "Đã tạo người dùng",
    USERS_CREATE_ERROR: "Tạo thất bại",
    USERS_FORM_USERNAME: "Username",
    USERS_FORM_USERNAME_PLACEHOLDER: "VD: user01",
    USERS_FORM_PASSWORD: "Mật khẩu",
    USERS_FORM_PASSWORD_PLACEHOLDER: "Tối thiểu 6 ký tự",
    USERS_FORM_LAST_NAME: "Họ",
    USERS_FORM_FIRST_NAME: "Tên",
    USERS_FORM_BIRTHDAY: "Ngày sinh",
    USERS_FORM_GENDER: "Giới tính",
    USERS_FORM_GENDER_OTHER: "Không xác định",
    USERS_FORM_GENDER_MALE: "Nam",
    USERS_FORM_GENDER_FEMALE: "Nữ",
    USERS_FORM_ROLE: "Vai trò",
    USERS_FORM_ROLE_PLACEHOLDER: "Chọn vai trò",
    USERS_ROLE_PLACEHOLDER: "Chọn vai trò",

    // Roles & permissions page
    ROLES_TITLE: "Phân Quyền",
    ROLES_SUBTITLE: "Quản lý vai trò và ma trận quyền hạn truy cập tài nguyên",
    ROLES_CREATE: "Tạo Vai Trò",
    ROLES_MANAGE_RESOURCES: "Quản Lý Tài Nguyên",
    ROLES_EDIT: "Chỉnh sửa",
    ROLES_SAVE_PERMS: "Lưu",
    ROLES_CREATE_DIALOG_TITLE: "Tạo Vai Trò Mới",
    ROLES_CREATE_DIALOG_DESC: "Thêm vai trò mới để phân quyền cho người dùng.",
    ROLES_EDIT_DIALOG_TITLE: "Chỉnh Sửa Vai Trò",
    ROLES_EDIT_DIALOG_DESC: "Cập nhật thông tin vai trò trong hệ thống.",
    ROLES_FORM_NAME: "Tên vai trò",
    ROLES_FORM_NAME_PLACEHOLDER: "VD: Moderator, Reviewer...",
    ROLES_FORM_LEVEL: "Cấp độ (Level)",
    ROLES_FORM_LEVEL_HINT: "0 = cao nhất (Admin), số càng lớn = quyền hạn càng thấp",
    ROLES_CREATE_SUCCESS: "Đã tạo vai trò",
    ROLES_UPDATE_SUCCESS: "Đã cập nhật vai trò",
    ROLES_SAVE_ERROR: "Lưu vai trò thất bại",
    ROLES_PERMS_SUCCESS: "Đã lưu quyền hạn",
    ROLES_PERMS_ERROR: "Lưu quyền hạn thất bại",
    RESOURCES_DIALOG_TITLE: "Quản Lý Tài Nguyên",
    RESOURCES_DIALOG_DESC: "Thêm, sửa hoặc xóa các tài nguyên được bảo vệ trong hệ thống phân quyền.",
    RESOURCES_COL_KEY: "Key",
    RESOURCES_COL_DESC: "Mô tả",
    RESOURCES_KEY_LABEL: "Key",
    RESOURCES_KEY_PLACEHOLDER: "VD: submission",
    RESOURCES_DESC_LABEL: "Mô tả",
    RESOURCES_DESC_PLACEHOLDER: "VD: Bài nộp của người dùng",
    RESOURCES_ADD: "Thêm",
    RESOURCES_SEARCH_PLACEHOLDER: "Tìm tài nguyên...",
    RESOURCES_EMPTY: "Không tìm thấy tài nguyên nào.",
    RESOURCES_CREATE_SUCCESS: "Đã thêm tài nguyên",
    RESOURCES_CREATE_ERROR: "Thêm tài nguyên thất bại",
    RESOURCES_UPDATE_SUCCESS: "Đã cập nhật tài nguyên",
    RESOURCES_UPDATE_ERROR: "Cập nhật tài nguyên thất bại",
    RESOURCES_DELETE_SUCCESS: "Đã xoá tài nguyên",
    RESOURCES_DELETE_ERROR: "Xoá tài nguyên thất bại",

    // Shared form field labels
    FIELDS: {
      NAME: "Tên",
      NAME_PLACEHOLDER: "Nhập tên...",
      DESCRIPTION: "Mô tả",
      DESCRIPTION_PLACEHOLDER: "Nhập mô tả (tuỳ chọn)...",
      CODE: "Mã code",
      CODE_PLACEHOLDER: "VD: FIRE",
      WEIGHT: "Trọng số",
      MIN_RATING: "Rating tối thiểu",
      MIN_EXP: "EXP tối thiểu",
      LEVEL_NUM: "Cấp độ",
      EXP_REWARD: "EXP thưởng",
      TYPE: "Loại",
      TYPE_ROOT_BONE: "Căn Cốt",
      TYPE_TALENT: "Thiên Phú",
      RARITY: "Phẩm chất",
      SELECT_RARITY_PLACEHOLDER: "Chọn phẩm chất...",
      ELEMENT: "Ngũ Hành",
      DIFFICULTY: "Độ khó",
    },

    // Ranks
    RANKS: {
      TITLE: "Danh Hiệu",
      SUBTITLE: "Quản lý các danh hiệu xếp hạng",
      CREATE: "Tạo Danh Hiệu",
      SEARCH_PLACEHOLDER: "Tìm theo tên...",
      EMPTY: "Chưa có danh hiệu nào",
      DIALOG_CREATE_TITLE: "Tạo Danh Hiệu Mới",
      DIALOG_CREATE_DESC: "Thêm danh hiệu mới vào hệ thống.",
      DIALOG_EDIT_TITLE: "Chỉnh Sửa Danh Hiệu",
      DIALOG_EDIT_DESC: "Cập nhật thông tin danh hiệu.",
      COL_NAME: "Tên",
      COL_MIN_RATING: "Rating tối thiểu",
      COL_DESC: "Mô tả",
    },

    // Levels
    LEVELS: {
      TITLE: "Cảnh Giới",
      SUBTITLE: "Quản lý các cảnh giới tu luyện",
      CREATE: "Tạo Cảnh Giới",
      SEARCH_PLACEHOLDER: "Tìm theo tên...",
      EMPTY: "Chưa có cảnh giới nào",
      DIALOG_CREATE_TITLE: "Tạo Cảnh Giới Mới",
      DIALOG_CREATE_DESC: "Thêm cảnh giới mới vào hệ thống.",
      DIALOG_EDIT_TITLE: "Chỉnh Sửa Cảnh Giới",
      DIALOG_EDIT_DESC: "Cập nhật thông tin cảnh giới.",
      COL_NAME: "Tên",
      COL_MIN_EXP: "EXP tối thiểu",
      COL_DESC: "Mô tả",
    },

    // Elements
    ELEMENTS: {
      TITLE: "Ngũ Hành",
      SUBTITLE: "Quản lý các hệ ngũ hành linh căn",
      CREATE: "Tạo Ngũ Hành",
      SEARCH_PLACEHOLDER: "Tìm theo tên...",
      EMPTY: "Chưa có ngũ hành nào",
      DIALOG_CREATE_TITLE: "Tạo Ngũ Hành Mới",
      DIALOG_CREATE_DESC: "Thêm ngũ hành mới vào hệ thống.",
      DIALOG_EDIT_TITLE: "Chỉnh Sửa Ngũ Hành",
      DIALOG_EDIT_DESC: "Cập nhật thông tin ngũ hành.",
      COL_NAME: "Tên",
      COL_CODE: "Mã code",
      COL_DESC: "Mô tả",
    },

    // Difficulties
    DIFFICULTIES: {
      TITLE: "Độ Khó",
      SUBTITLE: "Quản lý các mức độ khó của bài tập",
      CREATE: "Tạo Độ Khó",
      SEARCH_PLACEHOLDER: "Tìm theo tên...",
      EMPTY: "Chưa có độ khó nào",
      DIALOG_CREATE_TITLE: "Tạo Độ Khó Mới",
      DIALOG_CREATE_DESC: "Thêm mức độ khó mới vào hệ thống.",
      DIALOG_EDIT_TITLE: "Chỉnh Sửa Độ Khó",
      DIALOG_EDIT_DESC: "Cập nhật thông tin độ khó.",
      COL_NAME: "Tên",
      COL_LEVEL: "Cấp độ",
      COL_EXP: "EXP thưởng",
      COL_DESC: "Mô tả",
    },

    // Rarities
    RARITIES: {
      TITLE: "Phẩm Chất",
      SUBTITLE: "Quản lý các bậc phẩm chất vật phẩm",
      CREATE: "Tạo Phẩm Chất",
      SEARCH_PLACEHOLDER: "Tìm theo tên...",
      EMPTY: "Chưa có phẩm chất nào",
      DIALOG_CREATE_TITLE: "Tạo Phẩm Chất Mới",
      DIALOG_CREATE_DESC: "Thêm phẩm chất mới vào hệ thống.",
      DIALOG_EDIT_TITLE: "Chỉnh Sửa Phẩm Chất",
      DIALOG_EDIT_DESC: "Cập nhật thông tin phẩm chất.",
      COL_NAME: "Tên",
      COL_CODE: "Mã code",
      COL_WEIGHT: "Trọng số",
      COL_DESC: "Mô tả",
    },

    // Traits
    TRAITS: {
      TITLE: "Căn Cốt & Thiên Phú",
      SUBTITLE: "Quản lý các thiên mệnh của người tu luyện",
      CREATE: "Tạo Thiên Mệnh",
      SEARCH_PLACEHOLDER: "Tìm theo tên...",
      EMPTY: "Chưa có thiên mệnh nào",
      DIALOG_CREATE_TITLE: "Tạo Thiên Mệnh Mới",
      DIALOG_CREATE_DESC: "Thêm căn cốt hoặc thiên phú mới vào hệ thống.",
      DIALOG_EDIT_TITLE: "Chỉnh Sửa Thiên Mệnh",
      DIALOG_EDIT_DESC: "Cập nhật thông tin thiên mệnh.",
      COL_NAME: "Tên",
      COL_TYPE: "Loại",
      COL_RARITY: "Phẩm chất",
      COL_DESC: "Mô tả",
      FILTER_TYPE_ALL: "Tất cả loại",
      FILTER_RARITY_ALL: "Tất cả phẩm chất",
    },

    // Tags
    TAGS: {
      TITLE: "Công Pháp (Tags)",
      SUBTITLE: "Quản lý các thẻ phân loại bài tập",
      CREATE: "Tạo Tag",
      SEARCH_PLACEHOLDER: "Tìm theo tên...",
      EMPTY: "Chưa có tag nào",
      DIALOG_CREATE_TITLE: "Tạo Tag Mới",
      DIALOG_CREATE_DESC: "Thêm tag mới vào hệ thống.",
      DIALOG_EDIT_TITLE: "Chỉnh Sửa Tag",
      DIALOG_EDIT_DESC: "Cập nhật thông tin tag.",
      COL_NAME: "Tên",
      COL_ELEMENTS: "Ngũ hành",
      COL_DESC: "Mô tả",
      FILTER_ELEMENT_ALL: "Tất cả ngũ hành",
    },

    // Problems (list page only — create/edit navigate to separate pages)
    PROBLEMS: {
      TITLE: "Bài Tập",
      SUBTITLE: "Quản lý bài tập và test cases",
      CREATE: "Tạo Bài Tập",
      SEARCH_PLACEHOLDER: "Tìm theo tiêu đề...",
      EMPTY: "Chưa có bài tập nào",
      FILTER_DIFFICULTY_ALL: "Tất cả độ khó",
      COL_TITLE: "Tiêu đề",
      COL_TAGS: "Tags",
      COL_DIFFICULTY: "Độ khó",
      COL_STATUS: "Trạng thái",
      COL_LIMITS: "Giới hạn",
    },

    // Contests
    CONTESTS: {
      TITLE: "Đại Hội Tỷ Thí",
      SUBTITLE: "Quản lý các cuộc thi lập trình",
      CREATE: "Tạo Đại Hội",
      SEARCH_PLACEHOLDER: "Tìm theo tiêu đề...",
      EMPTY: "Chưa có cuộc thi nào",
      COL_TITLE: "Tiêu đề",
      COL_STATUS: "Trạng thái",
      COL_START: "Bắt đầu",
      COL_END: "Kết thúc",
      COL_PARTICIPANTS: "Tham gia",
      DIALOG_CREATE_TITLE: "Tạo Đại Hội Mới",
      DIALOG_CREATE_DESC: "Tạo cuộc thi lập trình mới.",
      DIALOG_EDIT_TITLE: "Chỉnh Sửa Đại Hội",
      DIALOG_EDIT_DESC: "Cập nhật thông tin cuộc thi.",
      FORM_TITLE: "Tiêu đề",
      FORM_TITLE_PLACEHOLDER: "VD: Đại Hội Mùa Xuân 2026",
      FORM_DESCRIPTION: "Mô tả",
      FORM_DESCRIPTION_PLACEHOLDER: "Mô tả cuộc thi...",
      FORM_START_TIME: "Thời gian bắt đầu",
      FORM_END_TIME: "Thời gian kết thúc",
      FORM_MAX_PARTICIPANTS: "Giới hạn người tham gia",
      FORM_PROBLEM_IDS: "Danh sách bài tập (IDs)",
      FORM_PROBLEM_IDS_PLACEHOLDER: "VD: 1, 2, 3",
      FILTER_STATUS_ALL: "Tất cả trạng thái",
    },

    // Shared action toast messages
    CREATE_SUCCESS: "Tạo thành công",
    UPDATE_SUCCESS: "Cập nhật thành công",
    DELETE_SUCCESS: "Xoá thành công",
    LOAD_ERROR: "Không thể tải dữ liệu",
    SAVE_ERROR: "Thao tác thất bại",
    DELETE_ERROR: "Không thể xoá",
  },

  // Common
  COMMON: {
    LOADING: "Đang tải...",
    ERROR: "Có lỗi xảy ra",
    RETRY: "Thử lại",
    SAVE: "Lưu",
    CANCEL: "Hủy",
    DELETE: "Xóa",
    EDIT: "Sửa",
    CREATE: "Tạo Mới",
    SEARCH: "Tìm Kiếm",
    FILTER: "Lọc",
    NO_DATA: "Không có dữ liệu",
    PAGE: "Trang",
    OF: "trong số",
    PREVIOUS: "Trước",
    NEXT: "Tiếp",
  },
} as const;
