// Code generated by ent, DO NOT EDIT.

package userstats

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userstats type in the database.
	Label = "user_stats"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTotalExp holds the string denoting the total_exp field in the database.
	FieldTotalExp = "total_exp"
	// FieldCurrentLevelID holds the string denoting the current_level_id field in the database.
	FieldCurrentLevelID = "current_level_id"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeCurrentLevel holds the string denoting the current_level edge name in mutations.
	EdgeCurrentLevel = "current_level"
	// Table holds the table name of the userstats in the database.
	Table = "user_stats"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_stats"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// CurrentLevelTable is the table that holds the current_level relation/edge.
	CurrentLevelTable = "user_stats"
	// CurrentLevelInverseTable is the table name for the Level entity.
	// It exists in this package in order to avoid circular dependency with the "level" package.
	CurrentLevelInverseTable = "levels"
	// CurrentLevelColumn is the table column denoting the current_level relation/edge.
	CurrentLevelColumn = "current_level_id"
)

// Columns holds all SQL columns for userstats fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldDeletedBy,
	FieldUserID,
	FieldTotalExp,
	FieldCurrentLevelID,
	FieldRating,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/huynhanx03/judgify/internal/ent/generate/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTotalExp holds the default value on creation for the "total_exp" field.
	DefaultTotalExp int64
	// TotalExpValidator is a validator for the "total_exp" field. It is called by the builders before save.
	TotalExpValidator func(int64) error
	// DefaultRating holds the default value on creation for the "rating" field.
	DefaultRating int
)

// OrderOption defines the ordering options for the UserStats queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByTotalExp orders the results by the total_exp field.
func ByTotalExp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalExp, opts...).ToFunc()
}

// ByCurrentLevelID orders the results by the current_level_id field.
func ByCurrentLevelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentLevelID, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByCurrentLevelField orders the results by current_level field.
func ByCurrentLevelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCurrentLevelStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newCurrentLevelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CurrentLevelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CurrentLevelTable, CurrentLevelColumn),
	)
}
