// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/internal/problem/ports/test_case.go
//
// Generated by this command:
//
//	mockgen -source=./api/internal/problem/ports/test_case.go -destination=./api/internal/problem/mocks/mock_test_case.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/huynhanx03/judgify/internal/problem/core/dto"
	entity "github.com/huynhanx03/judgify/internal/problem/core/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTestCaseRepository is a mock of TestCaseRepository interface.
type MockTestCaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTestCaseRepositoryMockRecorder
	isgomock struct{}
}

// MockTestCaseRepositoryMockRecorder is the mock recorder for MockTestCaseRepository.
type MockTestCaseRepositoryMockRecorder struct {
	mock *MockTestCaseRepository
}

// NewMockTestCaseRepository creates a new mock instance.
func NewMockTestCaseRepository(ctrl *gomock.Controller) *MockTestCaseRepository {
	mock := &MockTestCaseRepository{ctrl: ctrl}
	mock.recorder = &MockTestCaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestCaseRepository) EXPECT() *MockTestCaseRepositoryMockRecorder {
	return m.recorder
}

// CountByProblemID mocks base method.
func (m *MockTestCaseRepository) CountByProblemID(ctx context.Context, problemID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByProblemID", ctx, problemID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByProblemID indicates an expected call of CountByProblemID.
func (mr *MockTestCaseRepositoryMockRecorder) CountByProblemID(ctx, problemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByProblemID", reflect.TypeOf((*MockTestCaseRepository)(nil).CountByProblemID), ctx, problemID)
}

// Create mocks base method.
func (m *MockTestCaseRepository) Create(ctx context.Context, e *entity.TestCase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTestCaseRepositoryMockRecorder) Create(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTestCaseRepository)(nil).Create), ctx, e)
}

// Delete mocks base method.
func (m *MockTestCaseRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTestCaseRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTestCaseRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockTestCaseRepository) Exists(ctx context.Context, id int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockTestCaseRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockTestCaseRepository)(nil).Exists), ctx, id)
}

// FindByProblemID mocks base method.
func (m *MockTestCaseRepository) FindByProblemID(ctx context.Context, problemID int) ([]*entity.TestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProblemID", ctx, problemID)
	ret0, _ := ret[0].([]*entity.TestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProblemID indicates an expected call of FindByProblemID.
func (mr *MockTestCaseRepositoryMockRecorder) FindByProblemID(ctx, problemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProblemID", reflect.TypeOf((*MockTestCaseRepository)(nil).FindByProblemID), ctx, problemID)
}

// Get mocks base method.
func (m *MockTestCaseRepository) Get(ctx context.Context, id int) (*entity.TestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.TestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTestCaseRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTestCaseRepository)(nil).Get), ctx, id)
}

// Update mocks base method.
func (m *MockTestCaseRepository) Update(ctx context.Context, e *entity.TestCase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTestCaseRepositoryMockRecorder) Update(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTestCaseRepository)(nil).Update), ctx, e)
}

// MockTestCaseService is a mock of TestCaseService interface.
type MockTestCaseService struct {
	ctrl     *gomock.Controller
	recorder *MockTestCaseServiceMockRecorder
	isgomock struct{}
}

// MockTestCaseServiceMockRecorder is the mock recorder for MockTestCaseService.
type MockTestCaseServiceMockRecorder struct {
	mock *MockTestCaseService
}

// NewMockTestCaseService creates a new mock instance.
func NewMockTestCaseService(ctrl *gomock.Controller) *MockTestCaseService {
	mock := &MockTestCaseService{ctrl: ctrl}
	mock.recorder = &MockTestCaseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestCaseService) EXPECT() *MockTestCaseServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTestCaseService) Create(ctx context.Context, req *dto.CreateTestCaseRequest) (*dto.TestCaseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.TestCaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTestCaseServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTestCaseService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockTestCaseService) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTestCaseServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTestCaseService)(nil).Delete), ctx, id)
}

// FindByProblemID mocks base method.
func (m *MockTestCaseService) FindByProblemID(ctx context.Context, problemID int) ([]*dto.TestCaseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProblemID", ctx, problemID)
	ret0, _ := ret[0].([]*dto.TestCaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProblemID indicates an expected call of FindByProblemID.
func (mr *MockTestCaseServiceMockRecorder) FindByProblemID(ctx, problemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProblemID", reflect.TypeOf((*MockTestCaseService)(nil).FindByProblemID), ctx, problemID)
}

// Get mocks base method.
func (m *MockTestCaseService) Get(ctx context.Context, id int) (*dto.TestCaseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*dto.TestCaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTestCaseServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTestCaseService)(nil).Get), ctx, id)
}

// Update mocks base method.
func (m *MockTestCaseService) Update(ctx context.Context, id int, req *dto.UpdateTestCaseRequest) (*dto.TestCaseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.TestCaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTestCaseServiceMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTestCaseService)(nil).Update), ctx, id, req)
}
