// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/internal/contest/ports/registration.go
//
// Generated by this command:
//
//	mockgen -source=./api/internal/contest/ports/registration.go -destination=./api/internal/contest/mocks/mock_registration.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/huynhanx03/judgify/internal/contest/core/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistrationRepository is a mock of RegistrationRepository interface.
type MockRegistrationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationRepositoryMockRecorder
	isgomock struct{}
}

// MockRegistrationRepositoryMockRecorder is the mock recorder for MockRegistrationRepository.
type MockRegistrationRepositoryMockRecorder struct {
	mock *MockRegistrationRepository
}

// NewMockRegistrationRepository creates a new mock instance.
func NewMockRegistrationRepository(ctrl *gomock.Controller) *MockRegistrationRepository {
	mock := &MockRegistrationRepository{ctrl: ctrl}
	mock.recorder = &MockRegistrationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationRepository) EXPECT() *MockRegistrationRepositoryMockRecorder {
	return m.recorder
}

// CountByContest mocks base method.
func (m *MockRegistrationRepository) CountByContest(ctx context.Context, contestID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByContest", ctx, contestID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByContest indicates an expected call of CountByContest.
func (mr *MockRegistrationRepositoryMockRecorder) CountByContest(ctx, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByContest", reflect.TypeOf((*MockRegistrationRepository)(nil).CountByContest), ctx, contestID)
}

// Create mocks base method.
func (m *MockRegistrationRepository) Create(ctx context.Context, contestID, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, contestID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRegistrationRepositoryMockRecorder) Create(ctx, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRegistrationRepository)(nil).Create), ctx, contestID, userID)
}

// Delete mocks base method.
func (m *MockRegistrationRepository) Delete(ctx context.Context, contestID, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, contestID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRegistrationRepositoryMockRecorder) Delete(ctx, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRegistrationRepository)(nil).Delete), ctx, contestID, userID)
}

// Exists mocks base method.
func (m *MockRegistrationRepository) Exists(ctx context.Context, contestID, userID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, contestID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockRegistrationRepositoryMockRecorder) Exists(ctx, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockRegistrationRepository)(nil).Exists), ctx, contestID, userID)
}

// FindByContest mocks base method.
func (m *MockRegistrationRepository) FindByContest(ctx context.Context, contestID int) ([]*entity.ContestRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByContest", ctx, contestID)
	ret0, _ := ret[0].([]*entity.ContestRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByContest indicates an expected call of FindByContest.
func (mr *MockRegistrationRepositoryMockRecorder) FindByContest(ctx, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByContest", reflect.TypeOf((*MockRegistrationRepository)(nil).FindByContest), ctx, contestID)
}

// MockRegistrationService is a mock of RegistrationService interface.
type MockRegistrationService struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationServiceMockRecorder
	isgomock struct{}
}

// MockRegistrationServiceMockRecorder is the mock recorder for MockRegistrationService.
type MockRegistrationServiceMockRecorder struct {
	mock *MockRegistrationService
}

// NewMockRegistrationService creates a new mock instance.
func NewMockRegistrationService(ctrl *gomock.Controller) *MockRegistrationService {
	mock := &MockRegistrationService{ctrl: ctrl}
	mock.recorder = &MockRegistrationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationService) EXPECT() *MockRegistrationServiceMockRecorder {
	return m.recorder
}

// IsRegistered mocks base method.
func (m *MockRegistrationService) IsRegistered(ctx context.Context, contestID, userID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRegistered", ctx, contestID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRegistered indicates an expected call of IsRegistered.
func (mr *MockRegistrationServiceMockRecorder) IsRegistered(ctx, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRegistered", reflect.TypeOf((*MockRegistrationService)(nil).IsRegistered), ctx, contestID, userID)
}

// Register mocks base method.
func (m *MockRegistrationService) Register(ctx context.Context, contestID, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, contestID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockRegistrationServiceMockRecorder) Register(ctx, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockRegistrationService)(nil).Register), ctx, contestID, userID)
}

// Unregister mocks base method.
func (m *MockRegistrationService) Unregister(ctx context.Context, contestID, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unregister", ctx, contestID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unregister indicates an expected call of Unregister.
func (mr *MockRegistrationServiceMockRecorder) Unregister(ctx, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockRegistrationService)(nil).Unregister), ctx, contestID, userID)
}
