// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/internal/contest/ports/contest.go
//
// Generated by this command:
//
//	mockgen -source=./api/internal/contest/ports/contest.go -destination=./api/internal/contest/mocks/mock_contest.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/huynhanx03/judgify/internal/contest/core/dto"
	entity "github.com/huynhanx03/judgify/internal/contest/core/entity"
	dto0 "github.com/huynhanx03/judgify/pkg/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockContestRepository is a mock of ContestRepository interface.
type MockContestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContestRepositoryMockRecorder
	isgomock struct{}
}

// MockContestRepositoryMockRecorder is the mock recorder for MockContestRepository.
type MockContestRepositoryMockRecorder struct {
	mock *MockContestRepository
}

// NewMockContestRepository creates a new mock instance.
func NewMockContestRepository(ctrl *gomock.Controller) *MockContestRepository {
	mock := &MockContestRepository{ctrl: ctrl}
	mock.recorder = &MockContestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContestRepository) EXPECT() *MockContestRepositoryMockRecorder {
	return m.recorder
}

// AddProblems mocks base method.
func (m *MockContestRepository) AddProblems(ctx context.Context, contestID int, problemIDs []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProblems", ctx, contestID, problemIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProblems indicates an expected call of AddProblems.
func (mr *MockContestRepositoryMockRecorder) AddProblems(ctx, contestID, problemIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProblems", reflect.TypeOf((*MockContestRepository)(nil).AddProblems), ctx, contestID, problemIDs)
}

// CountRegistrations mocks base method.
func (m *MockContestRepository) CountRegistrations(ctx context.Context, contestID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRegistrations", ctx, contestID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRegistrations indicates an expected call of CountRegistrations.
func (mr *MockContestRepositoryMockRecorder) CountRegistrations(ctx, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRegistrations", reflect.TypeOf((*MockContestRepository)(nil).CountRegistrations), ctx, contestID)
}

// Create mocks base method.
func (m *MockContestRepository) Create(ctx context.Context, e *entity.Contest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockContestRepositoryMockRecorder) Create(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContestRepository)(nil).Create), ctx, e)
}

// Delete mocks base method.
func (m *MockContestRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockContestRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContestRepository)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockContestRepository) Find(ctx context.Context, opts *dto0.QueryOptions) (*dto0.Paginated[*entity.Contest], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, opts)
	ret0, _ := ret[0].(*dto0.Paginated[*entity.Contest])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockContestRepositoryMockRecorder) Find(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockContestRepository)(nil).Find), ctx, opts)
}

// FindIDsByStatus mocks base method.
func (m *MockContestRepository) FindIDsByStatus(ctx context.Context, status string) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIDsByStatus", ctx, status)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIDsByStatus indicates an expected call of FindIDsByStatus.
func (mr *MockContestRepositoryMockRecorder) FindIDsByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIDsByStatus", reflect.TypeOf((*MockContestRepository)(nil).FindIDsByStatus), ctx, status)
}

// Get mocks base method.
func (m *MockContestRepository) Get(ctx context.Context, id int) (*entity.Contest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.Contest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockContestRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContestRepository)(nil).Get), ctx, id)
}

// GetProblemIDs mocks base method.
func (m *MockContestRepository) GetProblemIDs(ctx context.Context, contestID int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProblemIDs", ctx, contestID)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProblemIDs indicates an expected call of GetProblemIDs.
func (mr *MockContestRepositoryMockRecorder) GetProblemIDs(ctx, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProblemIDs", reflect.TypeOf((*MockContestRepository)(nil).GetProblemIDs), ctx, contestID)
}

// RemoveAllProblems mocks base method.
func (m *MockContestRepository) RemoveAllProblems(ctx context.Context, contestID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllProblems", ctx, contestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllProblems indicates an expected call of RemoveAllProblems.
func (mr *MockContestRepositoryMockRecorder) RemoveAllProblems(ctx, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllProblems", reflect.TypeOf((*MockContestRepository)(nil).RemoveAllProblems), ctx, contestID)
}

// Update mocks base method.
func (m *MockContestRepository) Update(ctx context.Context, e *entity.Contest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockContestRepositoryMockRecorder) Update(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContestRepository)(nil).Update), ctx, e)
}

// UpdateStatus mocks base method.
func (m *MockContestRepository) UpdateStatus(ctx context.Context, id int, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockContestRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockContestRepository)(nil).UpdateStatus), ctx, id, status)
}

// MockContestService is a mock of ContestService interface.
type MockContestService struct {
	ctrl     *gomock.Controller
	recorder *MockContestServiceMockRecorder
	isgomock struct{}
}

// MockContestServiceMockRecorder is the mock recorder for MockContestService.
type MockContestServiceMockRecorder struct {
	mock *MockContestService
}

// NewMockContestService creates a new mock instance.
func NewMockContestService(ctrl *gomock.Controller) *MockContestService {
	mock := &MockContestService{ctrl: ctrl}
	mock.recorder = &MockContestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContestService) EXPECT() *MockContestServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockContestService) Create(ctx context.Context, authorID int, req *dto.CreateContestRequest) (*dto.ContestResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, authorID, req)
	ret0, _ := ret[0].(*dto.ContestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockContestServiceMockRecorder) Create(ctx, authorID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContestService)(nil).Create), ctx, authorID, req)
}

// Delete mocks base method.
func (m *MockContestService) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockContestServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContestService)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockContestService) Find(ctx context.Context, opts *dto0.QueryOptions) (*dto0.Paginated[*dto.ContestResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, opts)
	ret0, _ := ret[0].(*dto0.Paginated[*dto.ContestResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockContestServiceMockRecorder) Find(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockContestService)(nil).Find), ctx, opts)
}

// Get mocks base method.
func (m *MockContestService) Get(ctx context.Context, id, userID int) (*dto.ContestResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id, userID)
	ret0, _ := ret[0].(*dto.ContestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockContestServiceMockRecorder) Get(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContestService)(nil).Get), ctx, id, userID)
}

// Update mocks base method.
func (m *MockContestService) Update(ctx context.Context, id int, req *dto.UpdateContestRequest) (*dto.ContestResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.ContestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockContestServiceMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContestService)(nil).Update), ctx, id, req)
}
