// Code generated by ent, DO NOT EDIT.

package problem

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the problem type in the database.
	Label = "problem"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldDifficultyID holds the string denoting the difficulty_id field in the database.
	FieldDifficultyID = "difficulty_id"
	// FieldTimeLimitMs holds the string denoting the time_limit_ms field in the database.
	FieldTimeLimitMs = "time_limit_ms"
	// FieldMemoryLimitKB holds the string denoting the memory_limit_kb field in the database.
	FieldMemoryLimitKB = "memory_limit_kb"
	// FieldAuthorID holds the string denoting the author_id field in the database.
	FieldAuthorID = "author_id"
	// FieldIsPublished holds the string denoting the is_published field in the database.
	FieldIsPublished = "is_published"
	// FieldSubmissionCount holds the string denoting the submission_count field in the database.
	FieldSubmissionCount = "submission_count"
	// FieldAcceptedCount holds the string denoting the accepted_count field in the database.
	FieldAcceptedCount = "accepted_count"
	// EdgeAuthor holds the string denoting the author edge name in mutations.
	EdgeAuthor = "author"
	// EdgeDifficulty holds the string denoting the difficulty edge name in mutations.
	EdgeDifficulty = "difficulty"
	// EdgeTestCases holds the string denoting the test_cases edge name in mutations.
	EdgeTestCases = "test_cases"
	// EdgeSubmissions holds the string denoting the submissions edge name in mutations.
	EdgeSubmissions = "submissions"
	// EdgeTags holds the string denoting the tags edge name in mutations.
	EdgeTags = "tags"
	// EdgeSolvers holds the string denoting the solvers edge name in mutations.
	EdgeSolvers = "solvers"
	// Table holds the table name of the problem in the database.
	Table = "problems"
	// AuthorTable is the table that holds the author relation/edge.
	AuthorTable = "problems"
	// AuthorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AuthorInverseTable = "users"
	// AuthorColumn is the table column denoting the author relation/edge.
	AuthorColumn = "author_id"
	// DifficultyTable is the table that holds the difficulty relation/edge.
	DifficultyTable = "problems"
	// DifficultyInverseTable is the table name for the Difficulty entity.
	// It exists in this package in order to avoid circular dependency with the "difficulty" package.
	DifficultyInverseTable = "difficulties"
	// DifficultyColumn is the table column denoting the difficulty relation/edge.
	DifficultyColumn = "difficulty_id"
	// TestCasesTable is the table that holds the test_cases relation/edge.
	TestCasesTable = "test_cases"
	// TestCasesInverseTable is the table name for the TestCase entity.
	// It exists in this package in order to avoid circular dependency with the "testcase" package.
	TestCasesInverseTable = "test_cases"
	// TestCasesColumn is the table column denoting the test_cases relation/edge.
	TestCasesColumn = "problem_id"
	// SubmissionsTable is the table that holds the submissions relation/edge.
	SubmissionsTable = "submissions"
	// SubmissionsInverseTable is the table name for the Submission entity.
	// It exists in this package in order to avoid circular dependency with the "submission" package.
	SubmissionsInverseTable = "submissions"
	// SubmissionsColumn is the table column denoting the submissions relation/edge.
	SubmissionsColumn = "problem_id"
	// TagsTable is the table that holds the tags relation/edge. The primary key declared below.
	TagsTable = "problem_tags"
	// TagsInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagsInverseTable = "tags"
	// SolversTable is the table that holds the solvers relation/edge.
	SolversTable = "user_solved_problems"
	// SolversInverseTable is the table name for the UserSolvedProblem entity.
	// It exists in this package in order to avoid circular dependency with the "usersolvedproblem" package.
	SolversInverseTable = "user_solved_problems"
	// SolversColumn is the table column denoting the solvers relation/edge.
	SolversColumn = "problem_id"
)

// Columns holds all SQL columns for problem fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldDeletedBy,
	FieldTitle,
	FieldDescription,
	FieldDifficultyID,
	FieldTimeLimitMs,
	FieldMemoryLimitKB,
	FieldAuthorID,
	FieldIsPublished,
	FieldSubmissionCount,
	FieldAcceptedCount,
}

var (
	// TagsPrimaryKey and TagsColumn2 are the table columns denoting the
	// primary key for the tags relation (M2M).
	TagsPrimaryKey = []string{"problem_id", "tag_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/huynhanx03/judgify/internal/ent/generate/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultTimeLimitMs holds the default value on creation for the "time_limit_ms" field.
	DefaultTimeLimitMs int
	// DefaultMemoryLimitKB holds the default value on creation for the "memory_limit_kb" field.
	DefaultMemoryLimitKB int
	// DefaultIsPublished holds the default value on creation for the "is_published" field.
	DefaultIsPublished bool
	// DefaultSubmissionCount holds the default value on creation for the "submission_count" field.
	DefaultSubmissionCount int
	// DefaultAcceptedCount holds the default value on creation for the "accepted_count" field.
	DefaultAcceptedCount int
)

// OrderOption defines the ordering options for the Problem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByDifficultyID orders the results by the difficulty_id field.
func ByDifficultyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDifficultyID, opts...).ToFunc()
}

// ByTimeLimitMs orders the results by the time_limit_ms field.
func ByTimeLimitMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeLimitMs, opts...).ToFunc()
}

// ByMemoryLimitKB orders the results by the memory_limit_kb field.
func ByMemoryLimitKB(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemoryLimitKB, opts...).ToFunc()
}

// ByAuthorID orders the results by the author_id field.
func ByAuthorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorID, opts...).ToFunc()
}

// ByIsPublished orders the results by the is_published field.
func ByIsPublished(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPublished, opts...).ToFunc()
}

// BySubmissionCount orders the results by the submission_count field.
func BySubmissionCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmissionCount, opts...).ToFunc()
}

// ByAcceptedCount orders the results by the accepted_count field.
func ByAcceptedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcceptedCount, opts...).ToFunc()
}

// ByAuthorField orders the results by author field.
func ByAuthorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthorStep(), sql.OrderByField(field, opts...))
	}
}

// ByDifficultyField orders the results by difficulty field.
func ByDifficultyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDifficultyStep(), sql.OrderByField(field, opts...))
	}
}

// ByTestCasesCount orders the results by test_cases count.
func ByTestCasesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTestCasesStep(), opts...)
	}
}

// ByTestCases orders the results by test_cases terms.
func ByTestCases(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTestCasesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySubmissionsCount orders the results by submissions count.
func BySubmissionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSubmissionsStep(), opts...)
	}
}

// BySubmissions orders the results by submissions terms.
func BySubmissions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubmissionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTagsCount orders the results by tags count.
func ByTagsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTagsStep(), opts...)
	}
}

// ByTags orders the results by tags terms.
func ByTags(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTagsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySolversCount orders the results by solvers count.
func BySolversCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSolversStep(), opts...)
	}
}

// BySolvers orders the results by solvers terms.
func BySolvers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSolversStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAuthorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
	)
}
func newDifficultyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DifficultyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DifficultyTable, DifficultyColumn),
	)
}
func newTestCasesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TestCasesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TestCasesTable, TestCasesColumn),
	)
}
func newSubmissionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubmissionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SubmissionsTable, SubmissionsColumn),
	)
}
func newTagsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TagsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, TagsTable, TagsPrimaryKey...),
	)
}
func newSolversStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SolversInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SolversTable, SolversColumn),
	)
}
