// Code generated by ent, DO NOT EDIT.

package usertagstats

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/huynhanx03/judgify/internal/ent/generate/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldEQ(FieldUserID, v))
}

// TagID applies equality check predicate on the "tag_id" field. It's identical to TagIDEQ.
func TagID(v int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldEQ(FieldTagID, v))
}

// SolvedCount applies equality check predicate on the "solved_count" field. It's identical to SolvedCountEQ.
func SolvedCount(v int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldEQ(FieldSolvedCount, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldNotIn(FieldUserID, vs...))
}

// TagIDEQ applies the EQ predicate on the "tag_id" field.
func TagIDEQ(v int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldEQ(FieldTagID, v))
}

// TagIDNEQ applies the NEQ predicate on the "tag_id" field.
func TagIDNEQ(v int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldNEQ(FieldTagID, v))
}

// TagIDIn applies the In predicate on the "tag_id" field.
func TagIDIn(vs ...int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldIn(FieldTagID, vs...))
}

// TagIDNotIn applies the NotIn predicate on the "tag_id" field.
func TagIDNotIn(vs ...int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldNotIn(FieldTagID, vs...))
}

// SolvedCountEQ applies the EQ predicate on the "solved_count" field.
func SolvedCountEQ(v int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldEQ(FieldSolvedCount, v))
}

// SolvedCountNEQ applies the NEQ predicate on the "solved_count" field.
func SolvedCountNEQ(v int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldNEQ(FieldSolvedCount, v))
}

// SolvedCountIn applies the In predicate on the "solved_count" field.
func SolvedCountIn(vs ...int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldIn(FieldSolvedCount, vs...))
}

// SolvedCountNotIn applies the NotIn predicate on the "solved_count" field.
func SolvedCountNotIn(vs ...int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldNotIn(FieldSolvedCount, vs...))
}

// SolvedCountGT applies the GT predicate on the "solved_count" field.
func SolvedCountGT(v int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldGT(FieldSolvedCount, v))
}

// SolvedCountGTE applies the GTE predicate on the "solved_count" field.
func SolvedCountGTE(v int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldGTE(FieldSolvedCount, v))
}

// SolvedCountLT applies the LT predicate on the "solved_count" field.
func SolvedCountLT(v int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldLT(FieldSolvedCount, v))
}

// SolvedCountLTE applies the LTE predicate on the "solved_count" field.
func SolvedCountLTE(v int) predicate.UserTagStats {
	return predicate.UserTagStats(sql.FieldLTE(FieldSolvedCount, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserTagStats {
	return predicate.UserTagStats(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserTagStats {
	return predicate.UserTagStats(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTag applies the HasEdge predicate on the "tag" edge.
func HasTag() predicate.UserTagStats {
	return predicate.UserTagStats(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TagTable, TagColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagWith applies the HasEdge predicate on the "tag" edge with a given conditions (other predicates).
func HasTagWith(preds ...predicate.Tag) predicate.UserTagStats {
	return predicate.UserTagStats(func(s *sql.Selector) {
		step := newTagStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserTagStats) predicate.UserTagStats {
	return predicate.UserTagStats(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserTagStats) predicate.UserTagStats {
	return predicate.UserTagStats(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserTagStats) predicate.UserTagStats {
	return predicate.UserTagStats(sql.NotPredicates(p))
}
